-- Seed for dim_rate_code - GENERATED, DO NOT EDIT BY HAND.
--
-- Regenerate together with src/lib/rateReferential.ts:
--     python scripts/generate-rate-referential.py "Global Rate Referential (1).xlsx"
--
-- Source: 'REFERENTIAL' sheet of Accor's Global Rate Referential, edition 2026-07-22.
-- 573 codes.
--
-- includes_breakfast is NULL for plan 'CONTRACT' and 'PACKAGE'. NULL means "the rate
-- cannot answer", which is NOT the same as FALSE. Collapsing it to FALSE is the exact
-- defect this table exists to prevent - it silently refused breakfast to 60 adults on
-- one real export.
--
-- Property-local codes (C01MRO, LDR, C20, TRIPRO, CREWESR, MASTBB and others) are
-- absent from Accor's global file and are NOT seeded here. Insert them with
-- is_in_global_referential = FALSE and includes_breakfast = NULL as they are
-- confirmed by someone with Opera rate-code access.

DELETE FROM dim_rate_code WHERE is_in_global_referential = TRUE;

INSERT INTO dim_rate_code
  (rate_code, rate_name, rate_family, meal_plan,
   includes_breakfast, includes_lunch, includes_dinner,
   is_in_global_referential, referential_version)
VALUES
  ('A10PCT', 'Ctrip Dual Loyalty Prepay 5%', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A10RA1', 'ALL MEMBERSHIP OFFER - 5% OFF FLEXIBLE RATE', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A10RB1', 'ALL MEMBERSHIP OFFER - Bed and Breakfast', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A15PCT', 'Ctrip Dual Loyalty Prepay 10%', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A15RA1', 'ALL MEMBERSHIP OFFER - Room Only', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A15RB1', 'ALL MEMBERSHIP OFFER - Bed and Breakfast', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A18PCT', 'Ctrip Dual Loyalty Prepay 15%', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A18RA1', 'ALL MEMBERSHIP OFFER - Room Only', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A18RB1', 'ALL MEMBERSHIP OFFER - Bed and Breakfast', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A30RB', 'ALL PLUS 2.0 Bed and Breakfast-30% Off', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A30RO', 'Accor Plus 2.0 Room Only-30% Off', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A40RB', 'ALL PLUS 2.0 Bed and Breakfast-40% Off', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A40RO', 'Accor Plus 2.0 Room Only-40% Off', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A50RB', 'ALL PLUS 2.0 Bed and Breakfast-50% Off', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('A50RO', 'Accor Plus 2.0 Room Only-50% Off', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('AAA', 'AAA/CAA Auto Association rate', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ACLBOD', 'ALL Guaranteed Room -  FLEXIBLE RATE', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ACO', 'ALL HEARTISTS RATE - ELIGIBLE TO ALL POINTS', 'Accor employee rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ACOFF', 'ALL HEARTISTS FRIENDS AND FAMILY RATE - ELIGIBLE TO ALL POINTS', 'Accor employee rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ACOMP', 'Casino Comp Chargeback Rate', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('AGCMD', 'ALL MEMBERSHIP OFFER', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('AMOBBB', 'ALL Accor+ ibis & Voyager- 15% OFF APP OFFER - BREAKFAST INCLUDED', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('AMOBRO', 'ALL Accor+ ibis & Voyager- 15% OFF APP OFFER', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('AP1', 'National/Regional Offer', 'Package/Promo', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('AP2', 'Semi Flexible Rate', 'Package/Promo', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('AP3', 'Hotel Package 1', 'Package/Promo', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('AP4', 'ESPECIAL HALF BOARD', 'Package/Promo', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('AP5', 'Hotel Package 3', 'Package/Promo', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('APOFBB', 'APP only offer BB', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('APPOFF', 'APP Only Offer', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('APPOHB', 'APP only offer HB', 'Accor Loyalty', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARA1', 'ALL Accor+ ibis & Voyager - 15% OFF FLEXIBLE RATE', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARA3', 'ALL Accor+ ibis & Voyager - 15% OFF SAVER RATE', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARA3L', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARA3M', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARA3S', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARA4', 'ALL Accor+ ibis & Voyager - 15% OFF ADVANCE SAVER RATE', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARA4L', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARA4M', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARA4S', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARAF', 'ALL Accor+ ibis & Voyager- 15% OFF PREPAID RATE', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARAF2', 'ALL Accor+ ibis & Voyager- 15% OFF SEMI-FLEXIBLE RATE', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARB1', 'ALL Accor+ ibis & Voyager - 15% OFF FLEXIBLE RATE - BREAKFAST INCLUDED', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARB3', 'ALL Accor+ ibis & Voyager - 15% OFF SAVER RATE - BREAKFAST INCLUDED', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARB3L', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARB3M', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARB3S', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARB4', 'ALL Accor+ ibis & Voyager - 15% OFF ADVANCE SAVER RATE - BREAKFAST INCLUDED', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARB4L', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARB4M', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARB4S', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARBF', 'ALL Accor+ ibis & Voyager- 15% OFF PREPAID RATE - BREAKFAST INCLUDED', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARBF2', 'ALL Accor+ ibis & Voyager- 15% OFF SEMI-FLEXIBLE RATE - BREAKFAST INCLUDED', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ARF1', 'ALL Accor+ ibis & Voyager-15% OFF FLEXIBLE RATE - FULL BOARD', 'Accor Loyalty', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARF3', 'ALL Accor+ ibis & Voyager-15% OFF  SAVER RATE - FULL BOARD', 'Accor Loyalty', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARF3L', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Discount Card/Membership Program', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARF3M', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Accor Loyalty', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARF3S', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Accor Loyalty', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARF4', 'ALL Accor+ ibis & Voyager-15% OFF ADVANCE SAVER RATE - FULL BOARD', 'Accor Loyalty', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARF4L', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Accor Loyalty', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARF4M', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Accor Loyalty', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARF4S', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Accor Loyalty', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARH1', 'ALL Accor+ ibis & Voyager-15% OFF FLEXIBLE RATE - HALF BOARD', 'Accor Loyalty', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARH3', 'ALL Accor+ ibis & Voyager-15% OFF  SAVER RATE - HALF BOARD', 'Accor Loyalty', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARH3L', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Accor Loyalty', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARH3M', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Accor Loyalty', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARH3S', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Accor Loyalty', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARH4', 'ALL Accor+ ibis & Voyager-15% OFF ADVANCE SAVER RATE - HALF BOARD', 'Accor Loyalty', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARH4L', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Accor Loyalty', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARH4M', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Accor Loyalty', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARH4S', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Accor Loyalty', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARI1', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF FLEXIBLE RATE', 'Accor Loyalty', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARI3', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF SAVER RATE', 'Accor Loyalty', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARI3L', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Accor Loyalty', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARI3M', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Accor Loyalty', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARI3S', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Accor Loyalty', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARI4', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF ADVANCE SAVER RATE', 'Accor Loyalty', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARI4L', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Accor Loyalty', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARI4M', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Accor Loyalty', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('ARI4S', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Accor Loyalty', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('AVC', 'Accor Vacation Club', 'Accor employee rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('B10PCT', 'Ctrip Dual Loyalty Prepay BB 5%', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('B15PCT', 'Ctrip Dual Loyalty Prepay BB 10%', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('B18PCT', 'Ctrip Dual Loyalty Prepay BB 15%', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('BAR3', 'Opaque rate', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('BGCI', 'Business Groups - Convention', 'Group rate', 'CONTRACT', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('BGPG', 'Pro & Incentive', 'Group rate', 'CONTRACT', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('BGRE', 'Residential Seminars', 'Group rate', 'CONTRACT', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('BLFBB', 'Black Friday BB', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('BLFRHB', 'Black Friday HB', 'Package/Promo', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('BLFRO', 'Black Friday RO', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('BNVN', 'HEARTISTS RATE - NOT ELIGIBLE TO ALL LOYALTY PROGRAM BENEFITS', 'Accor employee rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('BNVNFF', 'HEARTISTS FRIENDS AND FAMILY RATE - NOT ELIGIBLE TO ALL LOYALTY PROGRAM BENEFITS', 'Accor employee rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('BOOKIT', 'Ennismore PEEPS Rate', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('BPGA3', 'BUSINESS GROUPS ONLINE - ALL MEETING & EVENTS', 'Group rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('BPGB3', 'BUSINESS GROUPS ONLINE - ALL MEETING & EVENTS - BREAKFAST INCLUDED', 'Group rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CD0', 'Government Rate dynamic', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CFNAE', 'Complimentary Accor Employee', 'Complimentary', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CFNBB', 'Complimentary night', 'Complimentary', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CHXXXX', 'Static corporate contracts - Room only', 'Company rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('CN1BF1', 'CNY 1 Breakfast', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CN1BF2', 'CNY 1 Breakfast', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CN1BF3', 'CNY 1 Breakfast', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CN1SAR', '1YUAN BREAKFAST PROMOTION', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CNFBB', 'Complimentary night in BB', 'Complimentary', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CNFEP', 'Complimentary night in EP', 'Complimentary', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CNYP', 'ACCOR PLUS- CNY 1 breakfast', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('COBVE2', 'ALL-VISA: STAY CREDIT - ROOM UPGRADE - VIP', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('COBVE3', 'ALL-VISA: ROOM UPGRADE - VIP STATUS - LATE CHECKOUT', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('COBVU1', 'ALL-VISA: COMPLIMENTARY BREAKFAST - STAY CREDIT', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('COBVU2', 'ALL-VISA: STAY CREDIT - ROOM UPGRADE - VIP STATUS', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('COBVU3', 'ALL-VISA: ROOM UPGRADE - VIP STATUS - LATE CHECKOUT', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CP21', 'ACCOR STAFF BUSINESS RATE - Breakfast Free of Charge', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CQXXXX', 'Static corporate contracts - Room only', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('CZXXXX', 'Static corporate contracts - Bed & Breakfast', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DAF', 'STAY PLUS - 2 free nights per membership year', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DAY', 'ROOM FOR A DAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DAY1', 'ROOM FOR A DAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DAY2', 'ROOM FOR A DAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DCOVU1', 'ALL-VISA: COMPLIMENTARY BREAKFAST - STAY CREDIT', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DCOVU2', 'ALL-VISA: STAY CREDIT - ROOM UPGRADE - VIP STATUS', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DDAY', 'Day room rate Accor Plus', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DDAY1', 'Day room rate Accor Plus 1', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DDAY2', 'Day room rate Accor Plus 2', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DEXC', 'ALL Accor+ Explorer Exclusive Offers', 'Discount Card/Membership Program', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('DGBO', 'ALL Accor+ Explorer - More Escapes', 'Discount Card/Membership Program', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('DGBOL', 'ALL Accor+  Explorer - More Escapes - LONG STAY', 'Discount Card/Membership Program', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('DGBOM', 'ALL Accor+  Explorer - More Escapes - MEDIUM STAY', 'Discount Card/Membership Program', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('DGBOS', 'ALL Accor+  Explorer - More Escapes - SHORT STAY - SHORT STAY', 'Discount Card/Membership Program', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('DRA1', 'ALL Accor+ Explorer - 15% OFF FLEXIBLE RATE', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRA3', 'ALL Accor+ Explorer - 15% OFF SAVER RATE', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRA3L', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRA3M', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRA3S', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRA4', 'ALL Accor+ Explorer - 15% OFF ADVANCE SAVER RATE', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRA4L', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRA4M', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRA4S', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRAF', 'ALL ACCOR+ EXPLORER - 15% OFF PREPAID RATE', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRAF2', 'ALL Accor+ Explorer EVENT SEMI-FLEXIBLE RATE', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRB1', 'ALL Accor+ Explorer - 15% OFF FLEXIBLE RATE - BED AND BREAKFAST', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRB3', 'ALL Accor+ Explorer - 15% OFF SAVER RATE - BED AND BREAKFAST', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRB3L', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - LONG STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRB3M', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - MEDIUM STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRB3S', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - SHORT STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRB4', 'ALL Accor+ Explorer - 15% OFF ADVANCE SAVER RATE - BED AND BREAKFAST', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRB4L', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - LONG STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRB4M', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - MEDIUM STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRB4S', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - SHORT STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRBF', 'ALL ACCOR+ EXPLORER - 15% OFF PREPAID RATE - BREAKFAST INCLUDED', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRBF2', 'ALL Accor+ Explorer EVENT SEMI-FLEXIBLE RATE - BREAKFAST INCLUDED', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRC1', 'ACCOR PLUS - FLEXIBLE RATE - COMPLIMENTARY BREAKFAST ON ONE ROOM', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRC3', 'ACCOR PLUS - SAVER RATE - COMPLIMENTARY BREAKFAST ON ONE ROOM', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRC3L', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - LONG STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRC3M', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - MEDIUM STAY - MEDIUM STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRC3S', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - SHORT STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRC4', 'ACCOR PLUS - ADVANCE SAVER - COMPLIMENTARY BREAKFAST ON ONE ROOM', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRC4L', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - LONG STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRC4M', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - MEDIUM STAY - MEDIUM STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRC4S', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - SHORT STAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRCF', 'ACCOR PLUS - SPECIAL EVENT RATE - COMPLIMENTARY BREAKFAST EVERYDAY', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DREMGD', 'ACCOR PLUS Resort Mid Gold', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DREMPL', 'ACCOR PLUS Resort Mid Platinum', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DREMSI', 'ACCOR PLUS Resort Mid Silver', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRESGD', 'ACCOR PLUS Resort Sup Gold', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRESPL', 'ACCOR PLUS Resort Sup Platinium', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRESSI', 'ACCOR PLUS Resort Sup Silver', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('DRF1', 'ALL Accor+ Explorer - FLEXIBLE RATE - FULL BOARD', 'Discount Card/Membership Program', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRF3', 'ALL Accor+ Explorer - SAVER RATE - FULL BOARD', 'Discount Card/Membership Program', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRF3L', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Discount Card/Membership Program', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRF3M', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Discount Card/Membership Program', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRF3S', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Discount Card/Membership Program', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRF4', 'ALL Accor+ Explorer - ADVANCE SAVER RATE - FULL BOARD', 'Discount Card/Membership Program', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRF4L', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Discount Card/Membership Program', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRF4M', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Discount Card/Membership Program', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRF4S', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Discount Card/Membership Program', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRH1', 'ALL Accor+ Explorer - 15% OFF FLEXIBLE RATE - HALF BOARD', 'Discount Card/Membership Program', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRH3', 'ALL Accor+ Explorer - 15% OFF NON FLEXIBLE RATE - HALF BOARD', 'Discount Card/Membership Program', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRH3L', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Discount Card/Membership Program', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRH3M', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Discount Card/Membership Program', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRH3S', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Discount Card/Membership Program', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRH4', 'ALL Accor+ Explorer - 15% OFF NON FLEXIBLE RATE - HALF BOARD', 'Discount Card/Membership Program', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRH4L', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Discount Card/Membership Program', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRH4M', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Discount Card/Membership Program', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRH4S', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Discount Card/Membership Program', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRI1', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF FLEXIBLE RATE', 'Discount Card/Membership Program', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRI3', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF SAVER RATE', 'Discount Card/Membership Program', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRI3L', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - LONG STAY', 'Discount Card/Membership Program', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRI3M', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - MEDIUM STAY', 'Discount Card/Membership Program', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRI3S', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - SHORT STAY', 'Discount Card/Membership Program', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRI4', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE', 'Discount Card/Membership Program', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRI4L', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - LONG STAY', 'Discount Card/Membership Program', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRI4M', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - MEDIUM STAY', 'Discount Card/Membership Program', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DRI4S', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - SHORT STAY', 'Discount Card/Membership Program', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('DSO', 'ALL Accor+ Explorer - RED HOT ROOMS', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLAP1', 'National/Reg. Offer Indirect 1', 'Wholesaler/FIT', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('FLAP2', 'INDIRECT Semi Flexible Rate', 'Wholesaler/FIT', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('FLBEBB', 'Black Friday BB Expedia', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLBEHB', 'Black Friday HB Expeida', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLBERO', 'Black Friday RO Expedia', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLBFBB', 'Black Friday BB	OTA', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLBFHB', 'Black Friday HB OTA', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLBFRO', 'Black Friday RO OTA', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLDAY', 'INDIRECT ROOM FOR A DAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLDAY1', 'INDIRECT ROOM FOR A DAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLDAY2', 'INDIRECT ROOM FOR A DAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLDM1', 'INDIRECT APP ONLY OFFER 0pct RA1', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLDM10', 'INDIRECT APP ONLY OFFER', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMAP1', 'National/Reg. Offer Indirect 2', 'Wholesaler/FIT', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('FLMAP2', 'National/Reg. Offer 2 Indirect 2', 'Wholesaler/FIT', 'PACKAGE', NULL, NULL, NULL, TRUE, DATE '2026-07-22'),
  ('FLMBBB', 'APP ONLY OFFER BB 0PCT', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMCBB', 'Super Sales rate BB Expedia', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMCRO', 'Super Sales rate CTO', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMOBB', 'Mobile Offer BB OTA', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMRA1', 'INDIRECT CTO FLEXIBLE RATE', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMRA3', 'INDIRECT CTO SAVER RATE', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMRA4', 'INDIRECT CTO ADVANCE SAVER RATE', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMRB1', 'INDIRECT CTO FLEXIBLE RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMRB3', 'INDIRECT CTO SAVER RATE- BREAKFAST INCLUDED', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMRB4', 'INDIRECT CTO ADVANCE SAVER RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLMRF1', 'INDIRECT CTO FLEXIBLE RATE - FULL BOARD', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLMRF3', 'INDIRECT CTO SAVER RATE - FULL BOARD', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLMRF4', 'INDIRECT CTO ADVANCE SAVER RATE - FULL BOARD', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLMRH1', 'INDIRECT CTO FLEXIBLE RATE - HALF BOARD', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLMRH3', 'INDIRECT CTO SAVER RATE - HALF BOARD', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLMRH4', 'INDIRECT CTO ADVANCE SAVER RATE - HALF BOARD', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLMRI1', 'INDIRECT CTO ALL INCLUSIVE - FLEXIBLE RATE', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLMRI3', 'INDIRECT CTO ALL INCLUSIVE - SAVER RATE', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLMRI4', 'INDIRECT CTO ALL INCLUSIVE - ADVANCE SAVER RATE', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLOFAI', 'OFFAI Indirect 1', 'Package/Promo', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLOFBB', 'OFFBB Indirect 1', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLOFFB', 'OFFFB Indirect 1', 'Package/Promo', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLOFHB', 'OFFHB Indirect 1', 'Package/Promo', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLOFRO', 'OFFRO Indirect 1', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLPRM1', 'GCHUB INDIRECT OFFER 1', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLPRM2', 'GCHUB INDIRECT OFFER 2', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLPRM3', 'GCHUB INDIRECT OFFER 3', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA1', 'INDIRECT FLEXIBLE RATE', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA1L', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - LONG STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA1M', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - MEDIUM STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA1S', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - SHORT STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA3', 'INDIRECT SAVER RATE', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA3L', 'INDIRECT STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA3M', 'INDIRECT STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA3S', 'INDIRECT STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA4', 'INDIRECT ADVANCE SAVER RATE', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA4L', 'INDIRECT STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA4M', 'INDIRECT STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRA4S', 'INDIRECT STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRAEB', 'EARLY BIRD OFFER - INDIRECT', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRAF', 'INDIRECT EVENT PREPAID RATE', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRAF2', 'INDIRECT SEMI-FLEXIBLE RATE', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB1', 'INDIRECT FLEXIBLE RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB1L', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB1M', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB1S', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB3', 'INDIRECT SAVER RATE- BREAKFAST INCLUDED', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB3L', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB3M', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB3S', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB4', 'INDIRECT ADVANCE SAVER RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB4L', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB4M', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRB4S', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRBEB', 'EARLY BIRD OFFER - INDIRECT', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRBF', 'INDIRECT EVENT PREPAID RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRBF2', 'INDIRECT EVENT SEMI-FLEXIBLE RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLRF1', 'INDIRECT FLEXIBLE RATE - FULL BOARD', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRF3', 'INDIRECT SAVER RATE - FULL BOARD', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRF3L', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRF3M', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRF3S', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRF4', 'INDIRECT ADVANCE SAVER RATE - FULL BOARD', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRF4L', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRF4M', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRF4S', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRFEB', 'EARLY BIRD OFFER - INDIRECT', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRH1', 'INDIRECT FLEXIBLE RATE - HALF BOARD', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRH3', 'INDIRECT SAVER RATE - HALF BOARD', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRH3L', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRH3M', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRH3S', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRH4', 'INDIRECT ADVANCE SAVER RATE - HALF BOARD', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRH4L', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRH4M', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRH4S', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRHEB', 'EARLY BIRD OFFER - INDIRECT', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRI1', 'INDIRECT ALL INCLUSIVE - FLEXIBLE RATE', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRI3', 'INDIRECT ALL INCLUSIVE - SAVER RATE', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRI3L', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRI3M', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRI3S', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRI4', 'INDIRECT ALL INCLUSIVE - ADVANCE SAVER RATE', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRI4L', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRI4M', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRI4S', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLRIEB', 'EARLY BIRD OFFER - INDIRECT', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLSBB', 'Super Sale BB OTA/CTO', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLSEXA', 'Super Sales rate Expedia', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLSEXB', 'Super Sales rate BB Expedia', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FLSEXH', 'Super Sales rate HB Expedia', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLSHB', 'Super Sales rate OTA/CTO', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FLSUP', 'Super Sales rate OTA/CTO', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMLY', 'Family Offer - second room at -50%', 'Family rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMOFAI', 'OFFAI Indirect 2', 'Package/Promo', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMOFBB', 'OFFBB Indirect 2', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMOFFB', 'OFFFB Indirect 2', 'Package/Promo', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMOFHB', 'OFFHB Indirect 2', 'Package/Promo', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMOFRO', 'OFFRO Indirect 2', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRA1L', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - LONG STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRA1M', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - MEDIUM STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRA1S', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - SHORT STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRA3L', 'INDIRECT CTO STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRA3M', 'INDIRECT CTO STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRA3S', 'INDIRECT CTO STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRA4L', 'INDIRECT CTO STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRA4M', 'INDIRECT CTO STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRA4S', 'INDIRECT CTO STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRAEB', 'EARLY BIRD OFFER-INDIRECT 2', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRB1L', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRB1M', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRB1S', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRB3L', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRB3M', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRB3S', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRB4L', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRB4M', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRB4S', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRBEB', 'EARLY BIRD OFFER-INDIRECT 2', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMRF3L', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRF3M', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRF3S', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRF4L', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRF4M', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRF4S', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRFEB', 'EARLY BIRD OFFER-INDIRECT 2', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRH3L', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRH3M', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRH3S', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRH4L', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRH4M', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRH4S', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRHEB', 'EARLY BIRD OFFER-INDIRECT 2', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRI3L', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRI3M', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRI3S', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRI4L', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRI4M', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRI4S', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMRIEB', 'EARLY BIRD OFFER-INDIRECT 2', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('FMSEXA', 'Super Sales rate Expedia', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('FMSEXB', 'Super Sales rate BB Expedia', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('GOV', 'Government Rate static', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('HOUSE', 'House Use', 'Complimentary', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('HS1', 'Employees, Friends and Family - Flexible rate - eligible to ALL points', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('HS1BRN', 'ACCOR OWNER PARTNER RATE 1', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('HS3', 'Employees, Friends and Family - Saver rate - eligible to ALL points', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('HS3BRN', 'ACCOR OWNER PARTNER RATE 3', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('L10RA1', 'Lux Member Discount - Classic', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('L10RB1', 'Lux Member Discount - Classic', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('L15RA1', 'Lux Member Discount - Silver & Gold', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('L15RB1', 'Lux Member Discount - Silver & Gold', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('L18RA1', 'Lux Member Discount - Platinum+', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('L18RB1', 'Lux Member Discount - Platinum+', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('L19', 'Leisure Rate/L19', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LAXXXX', 'Static Leisure individual - Room only', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LBXXXX', 'Static Leisure individual - Bed and Breakfast', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LFXXXX', 'Static Leisure individual - Full Board', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('LHXXXX', 'Static Leisure individual - Half Board', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('LIXXXX', 'Static Leisure individual - All inclusive', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('LOCAL', 'AAPC Local Staff Rate', 'Accor employee rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXX20', 'Luxury program Promo 20% MIN5', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXX25', 'Luxury program Promo 25% MIN4', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXX30', 'Luxury program Promo 30% MIN3', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXXM1', 'Luxury program Master offer standard commission (10%)', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXXM2', 'Luxury program Master offer 20% commission on Suites', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXXMS', 'Luxury program Master offer 15% commission on Suites', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXXP3', 'Luxury program Promo Stay 3 Pay 2', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXXP4', 'Luxury program Promo Stay 4 Pay 3', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXXP5', 'Luxury program Promo Stay 5 Pay 4', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXXPC', 'Luxury program Promo Extra Hotel Credit', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('LXXXPX', 'Luxury program Promo 10%', 'Luxury rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('MCA', 'MasterCard Partnership Rate', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ME10EN', 'Dis-loyalty Flexible Rate', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ME20EN', 'Dis-loyalty Flexible Rate', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ME25EN', 'Dis-loyalty Flexible Rate', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ME30EN', 'Dis-loyalty Flexible Rate', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ME35EN', 'Dis-Loyalty Flexible Rate', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('ME50EN', 'Dis-loyalty Flexible Rate - opening hotels', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('MEOD', 'One day meeting', 'Group rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('MOBBB', 'Mobile Offer BB for Direct', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('MOBC', 'ALL - APP OFFER - COMPLIMENTARY BREAKFAST ON WEEKENDS', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('MOBRO', 'Mobile Offer RO for Direct', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('MODBB', 'Modifiable rate BB', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('MODIF', 'Modification rate', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('MRA1', 'Member Rate Discount Flexible', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('MRB1', 'Member Rate Discount Flexible BB', 'Accor Loyalty', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('NPROM1', 'GCHUB NONMEM OFFER 1', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('NPROM2', 'GCHUB NONMEM OFFER 2', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('NPROM3', 'GCHUB NONMEM OFFER 3', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('OFAIEX', 'Global Offer - AI EXP', 'Wholesaler/FIT', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('OFBBEX', 'Global Offer - BB EXP', 'Wholesaler/FIT', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('OFFAI', 'Global Offer - AI', 'Package/Promo', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('OFFBB', 'Global Offer - BB', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('OFFBEX', 'Global Offer - FB EXP', 'Wholesaler/FIT', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('OFFFB', 'Global Offer - FB', 'Package/Promo', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('OFFHB', 'Global Offer - HB', 'Package/Promo', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('OFFRO', 'Global Offer - RO', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('OFHBEX', 'Global Offer - HB EXP', 'Wholesaler/FIT', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('OFROEX', 'Global Offer - RO EXP', 'Wholesaler/FIT', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PAR1', 'PARTNERSHIP 1', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PAR2', 'PARTNERSHIP 2', 'Discount Card/Membership Program', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PAR3', 'PARTNERSHIP 3', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PAR4', 'PARTNERSHIP 4', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PAR5', 'PARTNERSHIP 5', 'Discount Card/Membership Program', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PPARB1', 'PARK AND STAY - BREAKFAST INCLUDED', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PPC', 'Exclusive - Partner rate (50% off)', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PPSF15', 'PARK, SLEEP AND FLY - 15 DAYS OF PARKING', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PPSF3', 'ACCOR PLUS - PARK, SLEEP AND FLY - 3 DAYS OF PARKING', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PPSF7', 'ACCOR PLUS - PARK, SLEEP AND FLY - 7 DAYS OF PARKING', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PPSG15', 'PARK, SLEEP AND GO - 15 DAYS OF PARKING', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PPSG3', 'PARK, SLEEP AND GO - 3 DAYS OF PARKING', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PPSG7', 'PARK, SLEEP AND GO - 7 DAYS OF PARKING', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PRB1C', 'ACCOR PLUS - ROMANTIC ESCAPES - BREAKFAST INCLUDED  - CHAMPAGNE AND LATE CHECK OUT', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PRB1W', 'ACCOR PLUS - ROMANTIC ESCAPES - BREAKFAST INCLUDED  - WINE AND LATE CHECK OUT', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PROM1', 'Local Offer – Dual Membership (can be customized by hotel)', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PROM2', 'Local Offer – Dual Membership (can be customized by hotel)', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PROM3', 'Local Offer – Dual Membership (can be customized by hotel)', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PSB3M', 'WELLNESS AND SPA STAY', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PSB3S', 'WELLNESS AND SPA DISCOVERY STAY', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('PSH3M', 'GOURMET AND SPA STAY', 'Package/Promo', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('PSH3S', 'GOURMET AND SPA DISCOVERY STAY', 'Package/Promo', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('R1D10', 'Dynamic Flexible Rate -10%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D11', 'Dynamic Flexible Rate -11%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D12', 'Dynamic Flexible Rate -12%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D13', 'Dynamic Flexible Rate -13%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D14', 'Dynamic Flexible Rate -14%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D15', 'Dynamic Flexible Rate -15%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D16', 'Dynamic Flexible Rate -16%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D17', 'Dynamic Flexible Rate -17%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D18', 'Dynamic Flexible Rate -18%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D19', 'Dynamic Flexible Rate -19%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D5', 'Dynamic Rate -5%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R1D9', 'Dynamic Flexible Rate -9%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R3D5', 'Dynamic Rates -5%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('R4D5', 'Dynamic Rates -5%', 'Company rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA1', 'FLEXIBLE RATE', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA1L', 'STAY LONGER AND SAVE - FLEXIBLE RATE - LONG STAY', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA1M', 'STAY LONGER AND SAVE - FLEXIBLE RATE - MEDIUM STAY', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA1S', 'STAY LONGER AND SAVE - FLEXIBLE RATE - SHORT STAY', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA3', 'SAVER RATE', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA3L', 'STAY LONGER AND SAVE RATE - LONG STAY', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA3M', 'STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA3S', 'STAY LONGER AND SAVE RATE - SHORT STAY', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA4', 'ADVANCE SAVER RATE', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA4L', 'STAY LONGER AND SAVE RATE - LONG STAY', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA4M', 'STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RA4S', 'STAY LONGER AND SAVE RATE - SHORT STAY', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RAC', 'Rack Rate/RAC', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RACINR', 'Rack Rate India (for taxes only)', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RAEB', 'EARLY BIRD OFFER', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RAF', 'EVENT PREPAID RATE', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RAF2', 'SEMI-FLEXIBLE RATE', 'Rack rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1', 'FLEXIBLE RATE - BREAKFAST INCLUDED', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D10', 'Dynamic Rate BB -10%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D11', 'Dynamic Rate BB -11%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D12', 'Dynamic Rate BB -12%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D13', 'Dynamic Rate BB -13%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D14', 'Dynamic Rate BB -14%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D15', 'Dynamic Rate BB -15%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D16', 'Dynamic Rate BB -16%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D17', 'Dynamic Rate BB -17%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D18', 'Dynamic Rate BB -18%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D5', 'Dynamic Rate BB -5%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1D9', 'Dynamic Rate BB -9%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1FCM', 'RB1 FCM Breakfast Plus', 'Travel agency rates', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1L', 'STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - LONG STAY', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1M', 'STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB1S', 'STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB3', 'SAVER RATE- BREAKFAST INCLUDED', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB3D5', 'Dynamic Rates RB3 -5%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB3L', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB3M', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB3S', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB4', 'ADVANCE SAVER RATE - BREAKFAST INCLUDED', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB4D5', 'Dynamic Rates RB4 -5%', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB4L', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB4M', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RB4S', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RBEB', 'EARLY BIRD OFFER', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RBF', 'EVENT PREPAID RATE - BREAKFAST INCLUDED', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RBF2', 'EVENT SEMI-FLEXIBLE RATE - BREAKFAST INCLUDED', 'Rack rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RC1', 'ALL - FLEXIBLE RATE - COMPLIMENTARY BREAKFAST', 'Accor Loyalty', 'ASPAC', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RC3', 'ALL - SAVER RATE - COMPLIMENTARY BREAKFAST', 'Accor Loyalty', 'ASPAC', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RC3L', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - LONG STAY', 'Accor Loyalty', 'ASPAC', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RC3M', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - MEDIUM STAY', 'Accor Loyalty', 'ASPAC', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RC3S', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - SHORT STAY', 'Accor Loyalty', 'ASPAC', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RC4', 'ALL - ADVANCE SAVER RATE - COMPLIMENTARY BREAKFAST', 'Accor Loyalty', 'ASPAC', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RC4L', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - LONG STAY', 'Accor Loyalty', 'ASPAC', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RC4M', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - MEDIUM STAY', 'Accor Loyalty', 'ASPAC', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RC4S', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - SHORT STAY', 'Accor Loyalty', 'ASPAC', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RCF', 'SPECIAL EVENT RATE - COMPLIMENTARY BREAKFAST', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RCF2', 'SPECIAL EVENT RATE - COMPLIMENTARY BREAKFAST', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RDMDA', 'ACCOR PLUS MOBILE ONLY OFFER - &0% OFF', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RECC', 'LUXURY RESIDENCE OWNER RECIPROCAL USE PROGRAM RATE', 'Accor employee rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('REMCL1', 'FLEXIBLE RATE : GET A 20 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('REMGD1', 'FLEXIBLE RATE : GET A 50 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('REMPL1', 'FLEXIBLE RATE : GET A 60 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('REMSI1', 'FLEXIBLE RATE : GET A 35 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RESCL1', 'FLEXIBLE RATE : GET A 50 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RESGD1', 'FLEXIBLE RATE : GET A 100 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RESON1', 'AccorHotels Residential Owner Platinum', 'Accor Loyalty', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RESPL1', 'FLEXIBLE RATE : GET A 120 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RESSI1', 'FLEXIBLE RATE : GET A 70 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('RF1', 'FLEXIBLE RATE - FULL BOARD', 'Rack rate', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RF3', 'SAVER RATE - FULL BOARD', 'Rack rate', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RF3L', 'STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Rack rate', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RF3M', 'STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Rack rate', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RF3S', 'STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Rack rate', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RF4', 'ADVANCE SAVER RATE - FULL BOARD', 'Rack rate', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RF4L', 'STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Rack rate', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RF4M', 'STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Rack rate', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RF4S', 'STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Rack rate', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RFEB', 'EARLY BIRD OFFER', 'Package/Promo', 'FB', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RH1', 'FLEXIBLE RATE - HALF BOARD', 'Rack rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('RH3', 'SAVER RATE - HALF BOARD', 'Rack rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('RH3L', 'STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Rack rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('RH3M', 'STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Rack rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('RH3S', 'STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Rack rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('RH4', 'ADVANCE SAVER RATE - HALF BOARD', 'Rack rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('RH4L', 'STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Rack rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('RH4M', 'STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Rack rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('RH4S', 'STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Rack rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('RHEB', 'EARLY BIRD OFFER', 'Package/Promo', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('RI1', 'ALL INCLUSIVE - FLEXIBLE RATE', 'Rack rate', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RI3', 'ALL INCLUSIVE - SAVER RATE', 'Rack rate', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RI3L', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Rack rate', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RI3M', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Rack rate', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RI3S', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Rack rate', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RI4', 'ALL INCLUSIVE - ADVANCE SAVER RATE', 'Rack rate', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RI4L', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Rack rate', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RI4M', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Rack rate', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RI4S', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Rack rate', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('RIEB', 'EARLY BIRD OFFER', 'Package/Promo', 'AI', TRUE, TRUE, TRUE, TRUE, DATE '2026-07-22'),
  ('SEN', 'Senior Citizen Rate', 'Travel agency rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('STARP', 'STAR PLUS', 'Travel agency rates', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('SUPBB', 'Super Sale BB Rate', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('SUPERS', 'Super Sales rate', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('SUPHB', 'Super Sale HB Rate', 'Package/Promo', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('TGLL', 'Leisure Groups', 'Group rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('TGLLHB', 'Leisure Groups HB', 'Group rate', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('TRB1PX', 'Accor SME programme with TMCs', 'Company rate', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VCHIC', 'VERYCHIC ROOM ONLY', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VCHICB', 'VERYCHIC BB', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VCHICH', 'VERYCHIC HALF BOARD', 'Package/Promo', 'HB', TRUE, FALSE, TRUE, TRUE, DATE '2026-07-22'),
  ('VCT', 'VERY CHIC TONIGHT RO', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VCTBB', 'VERY CHIC TONIGHT BB', 'Package/Promo', 'BB', TRUE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VITA', 'IBIS SPORT', 'Group rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUC10', 'Universal Voucher 10', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUC11', 'Universal Voucher 11', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUC12', 'Universal Voucher 12', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUC14', 'Universal Voucher 14', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUC15', 'Universal Voucher 15', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUCH1', 'Universal Voucher 1', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUCH2', 'Universal Voucher 2', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUCH3', 'Universal Voucher 3', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUCH4', 'Universal Voucher 4', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUCH5', 'Universal Voucher 5', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUCH6', 'Universal Voucher 6', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUCH7', 'Universal Voucher 7', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUCH8', 'Universal Voucher 8', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('VOUCH9', 'Universal Voucher 9', 'Package/Promo', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22'),
  ('WORKIT', 'Ennismore Business Travel', 'Accor employee rate', 'RO', FALSE, FALSE, FALSE, TRUE, DATE '2026-07-22');
