import type { WriteBatch } from 'firebase/firestore';
import { collection, commitInChunks, db, doc, getDocs, logOperaAuditTrail } from '../firebase';
import { isValidRoomNumber } from '../parsing';
import type { CheckIn, MealForecastItem } from '../types';
import { addDays } from './businessDate';
import { isLegacyForecast } from './guestImport';

/**
 * Finding and removing what earlier versions of the app wrote into production that is not real:
 *
 *  - daily_summaries: written ONLY by the historical seeder (random data) and the bulk uploader
 *    (fabricated actuals and forecasts). No real process ever wrote one.
 *  - forecasts without `source: 'package-forecast'`: written by the old parser that summed per-unit
 *    rows. 34 such Novotel documents are in production (214 breakfasts for 2 Sep; the file says 98).
 *  - check-ins flagged isSynthetic (the seeder's), or recorded against a "room" that is not a room
 *    number (one exists: room KGAGS on 31 Aug, checked in against the junk list).
 *  - guest documents whose id is not a room number: the 8 room-type codes (KGAGS, KGB, KGBBC, SDDMV,
 *    SKC, TWB, TWBBC, UNASSIGNED) written when a package forecast was imported as a guest list.
 *
 * The old "purge" deleted synthetic summaries and forecasts but left the synthetic check-ins - which
 * had overwritten real ones - in place forever.
 */
export interface MaintenanceScan {
  dailySummaries: string[];
  legacyForecasts: string[];
  checkins: Array<{ date: string; id: string; why: string }>;
  junkGuests: string[];
  daysScanned: number;
}

export async function scanForJunk(hotelId: string, today: string, lookbackDays = 120): Promise<MaintenanceScan> {
  const [summaries, forecasts, guests] = await Promise.all([
    getDocs(collection(db, 'hotels', hotelId, 'daily_summaries')),
    getDocs(collection(db, 'hotels', hotelId, 'forecasts')),
    getDocs(collection(db, 'hotels', hotelId, 'guests')),
  ]);
  const legacyForecasts = forecasts.docs.filter((d) => isLegacyForecast(d.data() as MealForecastItem)).map((d) => d.id);

  // Check-ins live under one sub-collection per day, so scan the days that synthetic or legacy
  // documents mention plus a recent window.
  const dates = new Set<string>([...summaries.docs.map((d) => d.id), ...legacyForecasts.filter((d) => d <= today)]);
  for (let i = 0; i < lookbackDays; i++) dates.add(addDays(today, -i));
  const sorted = [...dates].filter((d) => /^\d{4}-\d{2}-\d{2}$/.test(d)).sort();
  const snaps = await Promise.all(sorted.map((d) => getDocs(collection(db, 'hotels', hotelId, 'checkins', d, 'rooms'))));
  const checkins: MaintenanceScan['checkins'] = [];
  snaps.forEach((s, i) =>
    s.docs.forEach((d) => {
      const c = d.data() as CheckIn;
      if (c.isSynthetic) checkins.push({ date: sorted[i], id: d.id, why: 'generated by the historical seeder' });
      else if (!isValidRoomNumber(String(c.roomNumber ?? ''))) checkins.push({ date: sorted[i], id: d.id, why: `"${c.roomNumber}" is not a room` });
    })
  );

  return {
    dailySummaries: summaries.docs.map((d) => d.id).sort(),
    legacyForecasts: legacyForecasts.sort(),
    checkins,
    junkGuests: guests.docs.map((d) => d.id).filter((id) => !isValidRoomNumber(id)).sort(),
    daysScanned: sorted.length,
  };
}

export async function purgeJunk(hotelId: string, scan: MaintenanceScan): Promise<number> {
  const ops = [
    ...scan.dailySummaries.map((id) => doc(db, 'hotels', hotelId, 'daily_summaries', id)),
    ...scan.legacyForecasts.map((id) => doc(db, 'hotels', hotelId, 'forecasts', id)),
    ...scan.checkins.map((c) => doc(db, 'hotels', hotelId, 'checkins', c.date, 'rooms', c.id)),
    ...scan.junkGuests.map((id) => doc(db, 'hotels', hotelId, 'guests', id)),
  ].map((ref) => (batch: WriteBatch) => batch.delete(ref));
  await commitInChunks(ops);
  await logOperaAuditTrail(
    hotelId,
    'DATA_MAINTENANCE',
    `Data maintenance: removed ${scan.dailySummaries.length} fabricated daily summaries, ${scan.legacyForecasts.length} over-counted forecasts, ` +
      `${scan.checkins.length} synthetic or junk check-ins and ${scan.junkGuests.length} junk guest documents`
  );
  return ops.length;
}
