/**
 * Accor Global Rate Referential - GENERATED FILE, DO NOT EDIT BY HAND.
 *
 * Regenerate with:
 *     python scripts/generate-rate-referential.py "<workbook.xlsx>"
 *
 * Source: 'REFERENTIAL' sheet of Accor's Global Rate Referential workbook.
 * Codes: 573.  Plans: {"AI": 53, "ASPAC": 9, "BB": 155, "CONTRACT": 3, "FB": 53, "HB": 65, "PACKAGE": 14, "RO": 221}
 *
 * ## Read this before touching entitlement logic
 *
 * Lookups here are EXACT MATCH, never substring. The Novotel resort code is literally `HB4F8`
 * and a loose `HB` test reads it as Half Board. The same substring mistake is what this table
 * replaces: `hasMealEntitlement` used to scan the rate code for 'BB' / 'BF' / 'RB', which
 * refused breakfast to guests who were owed it.
 *
 * Three plan codes are NOT simple meal plans, and each is a trap:
 *
 *   'ASPAC'    The workbook text begins "RO (Room Only) on weekdays" and ends
 *              "ASPAC: BB on all days of the week". Chiang Mai is ASPAC, so these codes ARE
 *              breakfast every day. Reading only the first words inverts the answer - and the
 *              codes' own names say "COMPLIMENTARY BREAKFAST", which agrees with the override.
 *   'CONTRACT' Accor's text is "Accoriding the contract" (their typo). Inclusion lives on the
 *              group block contract; NO rate table can ever resolve these. Reaching the
 *              contract needs BLOCK_CODE, export column 26.
 *   'PACKAGE'  Inclusion depends on what the package bundles.
 *
 * For all three, `breakfastFromRate()` returns null - meaning "the rate cannot answer this" -
 * which is deliberately different from false.
 */

/** Compact rows: [code, plan, name, rateFamily]. */
type RawRow = [string, string, string, string];

const RAW: RawRow[] = [
  ['A10PCT', 'RO', 'Ctrip Dual Loyalty Prepay 5%', 'Accor Loyalty'],
  ['A10RA1', 'RO', 'ALL MEMBERSHIP OFFER - 5% OFF FLEXIBLE RATE', 'Accor Loyalty'],
  ['A10RB1', 'BB', 'ALL MEMBERSHIP OFFER - Bed and Breakfast', 'Accor Loyalty'],
  ['A15PCT', 'RO', 'Ctrip Dual Loyalty Prepay 10%', 'Accor Loyalty'],
  ['A15RA1', 'RO', 'ALL MEMBERSHIP OFFER - Room Only', 'Accor Loyalty'],
  ['A15RB1', 'BB', 'ALL MEMBERSHIP OFFER - Bed and Breakfast', 'Accor Loyalty'],
  ['A18PCT', 'RO', 'Ctrip Dual Loyalty Prepay 15%', 'Accor Loyalty'],
  ['A18RA1', 'RO', 'ALL MEMBERSHIP OFFER - Room Only', 'Accor Loyalty'],
  ['A18RB1', 'BB', 'ALL MEMBERSHIP OFFER - Bed and Breakfast', 'Accor Loyalty'],
  ['A30RB', 'BB', 'ALL PLUS 2.0 Bed and Breakfast-30% Off', 'Discount Card/Membership Program'],
  ['A30RO', 'RO', 'Accor Plus 2.0 Room Only-30% Off', 'Discount Card/Membership Program'],
  ['A40RB', 'BB', 'ALL PLUS 2.0 Bed and Breakfast-40% Off', 'Discount Card/Membership Program'],
  ['A40RO', 'RO', 'Accor Plus 2.0 Room Only-40% Off', 'Discount Card/Membership Program'],
  ['A50RB', 'BB', 'ALL PLUS 2.0 Bed and Breakfast-50% Off', 'Discount Card/Membership Program'],
  ['A50RO', 'RO', 'Accor Plus 2.0 Room Only-50% Off', 'Discount Card/Membership Program'],
  ['AAA', 'RO', 'AAA/CAA Auto Association rate', 'Company rate'],
  ['ACLBOD', 'RO', 'ALL Guaranteed Room -  FLEXIBLE RATE', 'Accor Loyalty'],
  ['ACO', 'RO', 'ALL HEARTISTS RATE - ELIGIBLE TO ALL POINTS', 'Accor employee rate'],
  ['ACOFF', 'RO', 'ALL HEARTISTS FRIENDS AND FAMILY RATE - ELIGIBLE TO ALL POINTS', 'Accor employee rate'],
  ['ACOMP', 'RO', 'Casino Comp Chargeback Rate', 'Discount Card/Membership Program'],
  ['AGCMD', 'RO', 'ALL MEMBERSHIP OFFER', 'Accor Loyalty'],
  ['AMOBBB', 'BB', 'ALL Accor+ ibis & Voyager- 15% OFF APP OFFER - BREAKFAST INCLUDED', 'Accor Loyalty'],
  ['AMOBRO', 'RO', 'ALL Accor+ ibis & Voyager- 15% OFF APP OFFER', 'Accor Loyalty'],
  ['AP1', 'PACKAGE', 'National/Regional Offer', 'Package/Promo'],
  ['AP2', 'PACKAGE', 'Semi Flexible Rate', 'Package/Promo'],
  ['AP3', 'PACKAGE', 'Hotel Package 1', 'Package/Promo'],
  ['AP4', 'PACKAGE', 'ESPECIAL HALF BOARD', 'Package/Promo'],
  ['AP5', 'PACKAGE', 'Hotel Package 3', 'Package/Promo'],
  ['APOFBB', 'BB', 'APP only offer BB', 'Accor Loyalty'],
  ['APPOFF', 'RO', 'APP Only Offer', 'Accor Loyalty'],
  ['APPOHB', 'HB', 'APP only offer HB', 'Accor Loyalty'],
  ['ARA1', 'RO', 'ALL Accor+ ibis & Voyager - 15% OFF FLEXIBLE RATE', 'Accor Loyalty'],
  ['ARA3', 'RO', 'ALL Accor+ ibis & Voyager - 15% OFF SAVER RATE', 'Accor Loyalty'],
  ['ARA3L', 'RO', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Accor Loyalty'],
  ['ARA3M', 'RO', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Accor Loyalty'],
  ['ARA3S', 'RO', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Accor Loyalty'],
  ['ARA4', 'RO', 'ALL Accor+ ibis & Voyager - 15% OFF ADVANCE SAVER RATE', 'Accor Loyalty'],
  ['ARA4L', 'RO', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Accor Loyalty'],
  ['ARA4M', 'RO', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Accor Loyalty'],
  ['ARA4S', 'RO', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Accor Loyalty'],
  ['ARAF', 'RO', 'ALL Accor+ ibis & Voyager- 15% OFF PREPAID RATE', 'Accor Loyalty'],
  ['ARAF2', 'RO', 'ALL Accor+ ibis & Voyager- 15% OFF SEMI-FLEXIBLE RATE', 'Accor Loyalty'],
  ['ARB1', 'BB', 'ALL Accor+ ibis & Voyager - 15% OFF FLEXIBLE RATE - BREAKFAST INCLUDED', 'Accor Loyalty'],
  ['ARB3', 'BB', 'ALL Accor+ ibis & Voyager - 15% OFF SAVER RATE - BREAKFAST INCLUDED', 'Accor Loyalty'],
  ['ARB3L', 'BB', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Accor Loyalty'],
  ['ARB3M', 'BB', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Accor Loyalty'],
  ['ARB3S', 'BB', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Accor Loyalty'],
  ['ARB4', 'BB', 'ALL Accor+ ibis & Voyager - 15% OFF ADVANCE SAVER RATE - BREAKFAST INCLUDED', 'Accor Loyalty'],
  ['ARB4L', 'BB', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Accor Loyalty'],
  ['ARB4M', 'BB', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Accor Loyalty'],
  ['ARB4S', 'BB', 'ALL Accor+ ibis & Voyager - 15% OFF STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Accor Loyalty'],
  ['ARBF', 'BB', 'ALL Accor+ ibis & Voyager- 15% OFF PREPAID RATE - BREAKFAST INCLUDED', 'Accor Loyalty'],
  ['ARBF2', 'BB', 'ALL Accor+ ibis & Voyager- 15% OFF SEMI-FLEXIBLE RATE - BREAKFAST INCLUDED', 'Accor Loyalty'],
  ['ARF1', 'FB', 'ALL Accor+ ibis & Voyager-15% OFF FLEXIBLE RATE - FULL BOARD', 'Accor Loyalty'],
  ['ARF3', 'FB', 'ALL Accor+ ibis & Voyager-15% OFF  SAVER RATE - FULL BOARD', 'Accor Loyalty'],
  ['ARF3L', 'FB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Discount Card/Membership Program'],
  ['ARF3M', 'FB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Accor Loyalty'],
  ['ARF3S', 'FB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Accor Loyalty'],
  ['ARF4', 'FB', 'ALL Accor+ ibis & Voyager-15% OFF ADVANCE SAVER RATE - FULL BOARD', 'Accor Loyalty'],
  ['ARF4L', 'FB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Accor Loyalty'],
  ['ARF4M', 'FB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Accor Loyalty'],
  ['ARF4S', 'FB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Accor Loyalty'],
  ['ARH1', 'HB', 'ALL Accor+ ibis & Voyager-15% OFF FLEXIBLE RATE - HALF BOARD', 'Accor Loyalty'],
  ['ARH3', 'HB', 'ALL Accor+ ibis & Voyager-15% OFF  SAVER RATE - HALF BOARD', 'Accor Loyalty'],
  ['ARH3L', 'HB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Accor Loyalty'],
  ['ARH3M', 'HB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Accor Loyalty'],
  ['ARH3S', 'HB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Accor Loyalty'],
  ['ARH4', 'HB', 'ALL Accor+ ibis & Voyager-15% OFF ADVANCE SAVER RATE - HALF BOARD', 'Accor Loyalty'],
  ['ARH4L', 'HB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Accor Loyalty'],
  ['ARH4M', 'HB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Accor Loyalty'],
  ['ARH4S', 'HB', 'ALL Accor+ ibis & Voyager-15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Accor Loyalty'],
  ['ARI1', 'AI', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF FLEXIBLE RATE', 'Accor Loyalty'],
  ['ARI3', 'AI', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF SAVER RATE', 'Accor Loyalty'],
  ['ARI3L', 'AI', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Accor Loyalty'],
  ['ARI3M', 'AI', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Accor Loyalty'],
  ['ARI3S', 'AI', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Accor Loyalty'],
  ['ARI4', 'AI', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF ADVANCE SAVER RATE', 'Accor Loyalty'],
  ['ARI4L', 'AI', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Accor Loyalty'],
  ['ARI4M', 'AI', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Accor Loyalty'],
  ['ARI4S', 'AI', 'ALL Accor+ ibis & Voyager- ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Accor Loyalty'],
  ['AVC', 'RO', 'Accor Vacation Club', 'Accor employee rate'],
  ['B10PCT', 'BB', 'Ctrip Dual Loyalty Prepay BB 5%', 'Accor Loyalty'],
  ['B15PCT', 'BB', 'Ctrip Dual Loyalty Prepay BB 10%', 'Accor Loyalty'],
  ['B18PCT', 'BB', 'Ctrip Dual Loyalty Prepay BB 15%', 'Accor Loyalty'],
  ['BAR3', 'RO', 'Opaque rate', 'Package/Promo'],
  ['BGCI', 'CONTRACT', 'Business Groups - Convention', 'Group rate'],
  ['BGPG', 'CONTRACT', 'Pro & Incentive', 'Group rate'],
  ['BGRE', 'CONTRACT', 'Residential Seminars', 'Group rate'],
  ['BLFBB', 'BB', 'Black Friday BB', 'Package/Promo'],
  ['BLFRHB', 'HB', 'Black Friday HB', 'Package/Promo'],
  ['BLFRO', 'RO', 'Black Friday RO', 'Package/Promo'],
  ['BNVN', 'RO', 'HEARTISTS RATE - NOT ELIGIBLE TO ALL LOYALTY PROGRAM BENEFITS', 'Accor employee rate'],
  ['BNVNFF', 'RO', 'HEARTISTS FRIENDS AND FAMILY RATE - NOT ELIGIBLE TO ALL LOYALTY PROGRAM BENEFITS', 'Accor employee rate'],
  ['BOOKIT', 'RO', 'Ennismore PEEPS Rate', 'Package/Promo'],
  ['BPGA3', 'RO', 'BUSINESS GROUPS ONLINE - ALL MEETING & EVENTS', 'Group rate'],
  ['BPGB3', 'BB', 'BUSINESS GROUPS ONLINE - ALL MEETING & EVENTS - BREAKFAST INCLUDED', 'Group rate'],
  ['CD0', 'RO', 'Government Rate dynamic', 'Company rate'],
  ['CFNAE', 'RO', 'Complimentary Accor Employee', 'Complimentary'],
  ['CFNBB', 'BB', 'Complimentary night', 'Complimentary'],
  ['CHXXXX', 'HB', 'Static corporate contracts - Room only', 'Company rate'],
  ['CN1BF1', 'BB', 'CNY 1 Breakfast', 'Accor Loyalty'],
  ['CN1BF2', 'BB', 'CNY 1 Breakfast', 'Accor Loyalty'],
  ['CN1BF3', 'BB', 'CNY 1 Breakfast', 'Accor Loyalty'],
  ['CN1SAR', 'BB', '1YUAN BREAKFAST PROMOTION', 'Accor Loyalty'],
  ['CNFBB', 'BB', 'Complimentary night in BB', 'Complimentary'],
  ['CNFEP', 'RO', 'Complimentary night in EP', 'Complimentary'],
  ['CNYP', 'BB', 'ACCOR PLUS- CNY 1 breakfast', 'Package/Promo'],
  ['COBVE2', 'RO', 'ALL-VISA: STAY CREDIT - ROOM UPGRADE - VIP', 'Discount Card/Membership Program'],
  ['COBVE3', 'RO', 'ALL-VISA: ROOM UPGRADE - VIP STATUS - LATE CHECKOUT', 'Discount Card/Membership Program'],
  ['COBVU1', 'BB', 'ALL-VISA: COMPLIMENTARY BREAKFAST - STAY CREDIT', 'Discount Card/Membership Program'],
  ['COBVU2', 'RO', 'ALL-VISA: STAY CREDIT - ROOM UPGRADE - VIP STATUS', 'Discount Card/Membership Program'],
  ['COBVU3', 'RO', 'ALL-VISA: ROOM UPGRADE - VIP STATUS - LATE CHECKOUT', 'Discount Card/Membership Program'],
  ['CP21', 'BB', 'ACCOR STAFF BUSINESS RATE - Breakfast Free of Charge', 'Company rate'],
  ['CQXXXX', 'RO', 'Static corporate contracts - Room only', 'Company rate'],
  ['CZXXXX', 'BB', 'Static corporate contracts - Bed & Breakfast', 'Company rate'],
  ['DAF', 'RO', 'STAY PLUS - 2 free nights per membership year', 'Discount Card/Membership Program'],
  ['DAY', 'RO', 'ROOM FOR A DAY', 'Package/Promo'],
  ['DAY1', 'RO', 'ROOM FOR A DAY', 'Package/Promo'],
  ['DAY2', 'RO', 'ROOM FOR A DAY', 'Package/Promo'],
  ['DCOVU1', 'BB', 'ALL-VISA: COMPLIMENTARY BREAKFAST - STAY CREDIT', 'Discount Card/Membership Program'],
  ['DCOVU2', 'RO', 'ALL-VISA: STAY CREDIT - ROOM UPGRADE - VIP STATUS', 'Discount Card/Membership Program'],
  ['DDAY', 'RO', 'Day room rate Accor Plus', 'Discount Card/Membership Program'],
  ['DDAY1', 'RO', 'Day room rate Accor Plus 1', 'Discount Card/Membership Program'],
  ['DDAY2', 'RO', 'Day room rate Accor Plus 2', 'Discount Card/Membership Program'],
  ['DEXC', 'PACKAGE', 'ALL Accor+ Explorer Exclusive Offers', 'Discount Card/Membership Program'],
  ['DGBO', 'PACKAGE', 'ALL Accor+ Explorer - More Escapes', 'Discount Card/Membership Program'],
  ['DGBOL', 'PACKAGE', 'ALL Accor+  Explorer - More Escapes - LONG STAY', 'Discount Card/Membership Program'],
  ['DGBOM', 'PACKAGE', 'ALL Accor+  Explorer - More Escapes - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DGBOS', 'PACKAGE', 'ALL Accor+  Explorer - More Escapes - SHORT STAY - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRA1', 'RO', 'ALL Accor+ Explorer - 15% OFF FLEXIBLE RATE', 'Discount Card/Membership Program'],
  ['DRA3', 'RO', 'ALL Accor+ Explorer - 15% OFF SAVER RATE', 'Discount Card/Membership Program'],
  ['DRA3L', 'RO', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Discount Card/Membership Program'],
  ['DRA3M', 'RO', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRA3S', 'RO', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRA4', 'RO', 'ALL Accor+ Explorer - 15% OFF ADVANCE SAVER RATE', 'Discount Card/Membership Program'],
  ['DRA4L', 'RO', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - LONG STAY', 'Discount Card/Membership Program'],
  ['DRA4M', 'RO', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRA4S', 'RO', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRAF', 'RO', 'ALL ACCOR+ EXPLORER - 15% OFF PREPAID RATE', 'Discount Card/Membership Program'],
  ['DRAF2', 'RO', 'ALL Accor+ Explorer EVENT SEMI-FLEXIBLE RATE', 'Discount Card/Membership Program'],
  ['DRB1', 'BB', 'ALL Accor+ Explorer - 15% OFF FLEXIBLE RATE - BED AND BREAKFAST', 'Discount Card/Membership Program'],
  ['DRB3', 'BB', 'ALL Accor+ Explorer - 15% OFF SAVER RATE - BED AND BREAKFAST', 'Discount Card/Membership Program'],
  ['DRB3L', 'BB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - LONG STAY', 'Discount Card/Membership Program'],
  ['DRB3M', 'BB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRB3S', 'BB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRB4', 'BB', 'ALL Accor+ Explorer - 15% OFF ADVANCE SAVER RATE - BED AND BREAKFAST', 'Discount Card/Membership Program'],
  ['DRB4L', 'BB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - LONG STAY', 'Discount Card/Membership Program'],
  ['DRB4M', 'BB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRB4S', 'BB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - BED AND BREAKFAST - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRBF', 'BB', 'ALL ACCOR+ EXPLORER - 15% OFF PREPAID RATE - BREAKFAST INCLUDED', 'Discount Card/Membership Program'],
  ['DRBF2', 'BB', 'ALL Accor+ Explorer EVENT SEMI-FLEXIBLE RATE - BREAKFAST INCLUDED', 'Discount Card/Membership Program'],
  ['DRC1', 'BB', 'ACCOR PLUS - FLEXIBLE RATE - COMPLIMENTARY BREAKFAST ON ONE ROOM', 'Discount Card/Membership Program'],
  ['DRC3', 'BB', 'ACCOR PLUS - SAVER RATE - COMPLIMENTARY BREAKFAST ON ONE ROOM', 'Discount Card/Membership Program'],
  ['DRC3L', 'BB', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - LONG STAY', 'Discount Card/Membership Program'],
  ['DRC3M', 'BB', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - MEDIUM STAY - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRC3S', 'BB', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRC4', 'BB', 'ACCOR PLUS - ADVANCE SAVER - COMPLIMENTARY BREAKFAST ON ONE ROOM', 'Discount Card/Membership Program'],
  ['DRC4L', 'BB', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - LONG STAY', 'Discount Card/Membership Program'],
  ['DRC4M', 'BB', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - MEDIUM STAY - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRC4S', 'BB', 'ACCOR PLUS - LONGER STAY - COMPLIMENTARY BREAKFAST ON ONE ROOM - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRCF', 'BB', 'ACCOR PLUS - SPECIAL EVENT RATE - COMPLIMENTARY BREAKFAST EVERYDAY', 'Discount Card/Membership Program'],
  ['DREMGD', 'RO', 'ACCOR PLUS Resort Mid Gold', 'Discount Card/Membership Program'],
  ['DREMPL', 'RO', 'ACCOR PLUS Resort Mid Platinum', 'Discount Card/Membership Program'],
  ['DREMSI', 'RO', 'ACCOR PLUS Resort Mid Silver', 'Discount Card/Membership Program'],
  ['DRESGD', 'RO', 'ACCOR PLUS Resort Sup Gold', 'Discount Card/Membership Program'],
  ['DRESPL', 'RO', 'ACCOR PLUS Resort Sup Platinium', 'Discount Card/Membership Program'],
  ['DRESSI', 'RO', 'ACCOR PLUS Resort Sup Silver', 'Discount Card/Membership Program'],
  ['DRF1', 'FB', 'ALL Accor+ Explorer - FLEXIBLE RATE - FULL BOARD', 'Discount Card/Membership Program'],
  ['DRF3', 'FB', 'ALL Accor+ Explorer - SAVER RATE - FULL BOARD', 'Discount Card/Membership Program'],
  ['DRF3L', 'FB', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Discount Card/Membership Program'],
  ['DRF3M', 'FB', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRF3S', 'FB', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRF4', 'FB', 'ALL Accor+ Explorer - ADVANCE SAVER RATE - FULL BOARD', 'Discount Card/Membership Program'],
  ['DRF4L', 'FB', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Discount Card/Membership Program'],
  ['DRF4M', 'FB', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRF4S', 'FB', 'ALL Accor+ Explorer - STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRH1', 'HB', 'ALL Accor+ Explorer - 15% OFF FLEXIBLE RATE - HALF BOARD', 'Discount Card/Membership Program'],
  ['DRH3', 'HB', 'ALL Accor+ Explorer - 15% OFF NON FLEXIBLE RATE - HALF BOARD', 'Discount Card/Membership Program'],
  ['DRH3L', 'HB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Discount Card/Membership Program'],
  ['DRH3M', 'HB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRH3S', 'HB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRH4', 'HB', 'ALL Accor+ Explorer - 15% OFF NON FLEXIBLE RATE - HALF BOARD', 'Discount Card/Membership Program'],
  ['DRH4L', 'HB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Discount Card/Membership Program'],
  ['DRH4M', 'HB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRH4S', 'HB', 'ALL Accor+ Explorer - 15% OFF STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRI1', 'AI', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF FLEXIBLE RATE', 'Discount Card/Membership Program'],
  ['DRI3', 'AI', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF SAVER RATE', 'Discount Card/Membership Program'],
  ['DRI3L', 'AI', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - LONG STAY', 'Discount Card/Membership Program'],
  ['DRI3M', 'AI', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRI3S', 'AI', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - SHORT STAY', 'Discount Card/Membership Program'],
  ['DRI4', 'AI', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE', 'Discount Card/Membership Program'],
  ['DRI4L', 'AI', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - LONG STAY', 'Discount Card/Membership Program'],
  ['DRI4M', 'AI', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - MEDIUM STAY', 'Discount Card/Membership Program'],
  ['DRI4S', 'AI', 'ALL Accor+ Explorer - ALL INCLUSIVE - 15% OFF STAY LONGER AND SAVE - SHORT STAY', 'Discount Card/Membership Program'],
  ['DSO', 'RO', 'ALL Accor+ Explorer - RED HOT ROOMS', 'Discount Card/Membership Program'],
  ['FLAP1', 'PACKAGE', 'National/Reg. Offer Indirect 1', 'Wholesaler/FIT'],
  ['FLAP2', 'PACKAGE', 'INDIRECT Semi Flexible Rate', 'Wholesaler/FIT'],
  ['FLBEBB', 'BB', 'Black Friday BB Expedia', 'Wholesaler/FIT'],
  ['FLBEHB', 'HB', 'Black Friday HB Expeida', 'Wholesaler/FIT'],
  ['FLBERO', 'RO', 'Black Friday RO Expedia', 'Wholesaler/FIT'],
  ['FLBFBB', 'BB', 'Black Friday BB	OTA', 'Wholesaler/FIT'],
  ['FLBFHB', 'HB', 'Black Friday HB OTA', 'Wholesaler/FIT'],
  ['FLBFRO', 'RO', 'Black Friday RO OTA', 'Wholesaler/FIT'],
  ['FLDAY', 'RO', 'INDIRECT ROOM FOR A DAY', 'Wholesaler/FIT'],
  ['FLDAY1', 'RO', 'INDIRECT ROOM FOR A DAY', 'Wholesaler/FIT'],
  ['FLDAY2', 'RO', 'INDIRECT ROOM FOR A DAY', 'Wholesaler/FIT'],
  ['FLDM1', 'RO', 'INDIRECT APP ONLY OFFER 0pct RA1', 'Wholesaler/FIT'],
  ['FLDM10', 'RO', 'INDIRECT APP ONLY OFFER', 'Wholesaler/FIT'],
  ['FLMAP1', 'PACKAGE', 'National/Reg. Offer Indirect 2', 'Wholesaler/FIT'],
  ['FLMAP2', 'PACKAGE', 'National/Reg. Offer 2 Indirect 2', 'Wholesaler/FIT'],
  ['FLMBBB', 'BB', 'APP ONLY OFFER BB 0PCT', 'Package/Promo'],
  ['FLMCBB', 'BB', 'Super Sales rate BB Expedia', 'Wholesaler/FIT'],
  ['FLMCRO', 'RO', 'Super Sales rate CTO', 'Wholesaler/FIT'],
  ['FLMOBB', 'BB', 'Mobile Offer BB OTA', 'Wholesaler/FIT'],
  ['FLMRA1', 'RO', 'INDIRECT CTO FLEXIBLE RATE', 'Wholesaler/FIT'],
  ['FLMRA3', 'RO', 'INDIRECT CTO SAVER RATE', 'Wholesaler/FIT'],
  ['FLMRA4', 'RO', 'INDIRECT CTO ADVANCE SAVER RATE', 'Wholesaler/FIT'],
  ['FLMRB1', 'BB', 'INDIRECT CTO FLEXIBLE RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT'],
  ['FLMRB3', 'BB', 'INDIRECT CTO SAVER RATE- BREAKFAST INCLUDED', 'Wholesaler/FIT'],
  ['FLMRB4', 'BB', 'INDIRECT CTO ADVANCE SAVER RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT'],
  ['FLMRF1', 'FB', 'INDIRECT CTO FLEXIBLE RATE - FULL BOARD', 'Wholesaler/FIT'],
  ['FLMRF3', 'FB', 'INDIRECT CTO SAVER RATE - FULL BOARD', 'Wholesaler/FIT'],
  ['FLMRF4', 'FB', 'INDIRECT CTO ADVANCE SAVER RATE - FULL BOARD', 'Wholesaler/FIT'],
  ['FLMRH1', 'HB', 'INDIRECT CTO FLEXIBLE RATE - HALF BOARD', 'Wholesaler/FIT'],
  ['FLMRH3', 'HB', 'INDIRECT CTO SAVER RATE - HALF BOARD', 'Wholesaler/FIT'],
  ['FLMRH4', 'HB', 'INDIRECT CTO ADVANCE SAVER RATE - HALF BOARD', 'Wholesaler/FIT'],
  ['FLMRI1', 'AI', 'INDIRECT CTO ALL INCLUSIVE - FLEXIBLE RATE', 'Wholesaler/FIT'],
  ['FLMRI3', 'AI', 'INDIRECT CTO ALL INCLUSIVE - SAVER RATE', 'Wholesaler/FIT'],
  ['FLMRI4', 'AI', 'INDIRECT CTO ALL INCLUSIVE - ADVANCE SAVER RATE', 'Wholesaler/FIT'],
  ['FLOFAI', 'AI', 'OFFAI Indirect 1', 'Package/Promo'],
  ['FLOFBB', 'BB', 'OFFBB Indirect 1', 'Package/Promo'],
  ['FLOFFB', 'FB', 'OFFFB Indirect 1', 'Package/Promo'],
  ['FLOFHB', 'HB', 'OFFHB Indirect 1', 'Package/Promo'],
  ['FLOFRO', 'RO', 'OFFRO Indirect 1', 'Package/Promo'],
  ['FLPRM1', 'BB', 'GCHUB INDIRECT OFFER 1', 'Wholesaler/FIT'],
  ['FLPRM2', 'BB', 'GCHUB INDIRECT OFFER 2', 'Wholesaler/FIT'],
  ['FLPRM3', 'BB', 'GCHUB INDIRECT OFFER 3', 'Wholesaler/FIT'],
  ['FLRA1', 'RO', 'INDIRECT FLEXIBLE RATE', 'Wholesaler/FIT'],
  ['FLRA1L', 'RO', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - LONG STAY', 'Wholesaler/FIT'],
  ['FLRA1M', 'RO', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRA1S', 'RO', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRA3', 'RO', 'INDIRECT SAVER RATE', 'Wholesaler/FIT'],
  ['FLRA3L', 'RO', 'INDIRECT STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT'],
  ['FLRA3M', 'RO', 'INDIRECT STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRA3S', 'RO', 'INDIRECT STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRA4', 'RO', 'INDIRECT ADVANCE SAVER RATE', 'Wholesaler/FIT'],
  ['FLRA4L', 'RO', 'INDIRECT STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT'],
  ['FLRA4M', 'RO', 'INDIRECT STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRA4S', 'RO', 'INDIRECT STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRAEB', 'RO', 'EARLY BIRD OFFER - INDIRECT', 'Wholesaler/FIT'],
  ['FLRAF', 'RO', 'INDIRECT EVENT PREPAID RATE', 'Wholesaler/FIT'],
  ['FLRAF2', 'RO', 'INDIRECT SEMI-FLEXIBLE RATE', 'Wholesaler/FIT'],
  ['FLRB1', 'BB', 'INDIRECT FLEXIBLE RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT'],
  ['FLRB1L', 'BB', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT'],
  ['FLRB1M', 'BB', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRB1S', 'BB', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRB3', 'BB', 'INDIRECT SAVER RATE- BREAKFAST INCLUDED', 'Wholesaler/FIT'],
  ['FLRB3L', 'BB', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT'],
  ['FLRB3M', 'BB', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRB3S', 'BB', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRB4', 'BB', 'INDIRECT ADVANCE SAVER RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT'],
  ['FLRB4L', 'BB', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT'],
  ['FLRB4M', 'BB', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRB4S', 'BB', 'INDIRECT STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRBEB', 'BB', 'EARLY BIRD OFFER - INDIRECT', 'Wholesaler/FIT'],
  ['FLRBF', 'BB', 'INDIRECT EVENT PREPAID RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT'],
  ['FLRBF2', 'BB', 'INDIRECT EVENT SEMI-FLEXIBLE RATE - BREAKFAST INCLUDED', 'Wholesaler/FIT'],
  ['FLRF1', 'FB', 'INDIRECT FLEXIBLE RATE - FULL BOARD', 'Wholesaler/FIT'],
  ['FLRF3', 'FB', 'INDIRECT SAVER RATE - FULL BOARD', 'Wholesaler/FIT'],
  ['FLRF3L', 'FB', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Wholesaler/FIT'],
  ['FLRF3M', 'FB', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRF3S', 'FB', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRF4', 'FB', 'INDIRECT ADVANCE SAVER RATE - FULL BOARD', 'Wholesaler/FIT'],
  ['FLRF4L', 'FB', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Wholesaler/FIT'],
  ['FLRF4M', 'FB', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRF4S', 'FB', 'INDIRECT STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRFEB', 'FB', 'EARLY BIRD OFFER - INDIRECT', 'Wholesaler/FIT'],
  ['FLRH1', 'HB', 'INDIRECT FLEXIBLE RATE - HALF BOARD', 'Wholesaler/FIT'],
  ['FLRH3', 'HB', 'INDIRECT SAVER RATE - HALF BOARD', 'Wholesaler/FIT'],
  ['FLRH3L', 'HB', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Wholesaler/FIT'],
  ['FLRH3M', 'HB', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRH3S', 'HB', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRH4', 'HB', 'INDIRECT ADVANCE SAVER RATE - HALF BOARD', 'Wholesaler/FIT'],
  ['FLRH4L', 'HB', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Wholesaler/FIT'],
  ['FLRH4M', 'HB', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRH4S', 'HB', 'INDIRECT STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRHEB', 'HB', 'EARLY BIRD OFFER - INDIRECT', 'Wholesaler/FIT'],
  ['FLRI1', 'AI', 'INDIRECT ALL INCLUSIVE - FLEXIBLE RATE', 'Wholesaler/FIT'],
  ['FLRI3', 'AI', 'INDIRECT ALL INCLUSIVE - SAVER RATE', 'Wholesaler/FIT'],
  ['FLRI3L', 'AI', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT'],
  ['FLRI3M', 'AI', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRI3S', 'AI', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRI4', 'AI', 'INDIRECT ALL INCLUSIVE - ADVANCE SAVER RATE', 'Wholesaler/FIT'],
  ['FLRI4L', 'AI', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT'],
  ['FLRI4M', 'AI', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FLRI4S', 'AI', 'INDIRECT ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT'],
  ['FLRIEB', 'AI', 'EARLY BIRD OFFER - INDIRECT', 'Wholesaler/FIT'],
  ['FLSBB', 'BB', 'Super Sale BB OTA/CTO', 'Wholesaler/FIT'],
  ['FLSEXA', 'RO', 'Super Sales rate Expedia', 'Wholesaler/FIT'],
  ['FLSEXB', 'BB', 'Super Sales rate BB Expedia', 'Wholesaler/FIT'],
  ['FLSEXH', 'HB', 'Super Sales rate HB Expedia', 'Wholesaler/FIT'],
  ['FLSHB', 'HB', 'Super Sales rate OTA/CTO', 'Wholesaler/FIT'],
  ['FLSUP', 'RO', 'Super Sales rate OTA/CTO', 'Wholesaler/FIT'],
  ['FMLY', 'RO', 'Family Offer - second room at -50%', 'Family rates'],
  ['FMOFAI', 'AI', 'OFFAI Indirect 2', 'Package/Promo'],
  ['FMOFBB', 'BB', 'OFFBB Indirect 2', 'Package/Promo'],
  ['FMOFFB', 'FB', 'OFFFB Indirect 2', 'Package/Promo'],
  ['FMOFHB', 'HB', 'OFFHB Indirect 2', 'Package/Promo'],
  ['FMOFRO', 'RO', 'OFFRO Indirect 2', 'Package/Promo'],
  ['FMRA1L', 'RO', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - LONG STAY', 'Wholesaler/FIT'],
  ['FMRA1M', 'RO', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRA1S', 'RO', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRA3L', 'RO', 'INDIRECT CTO STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT'],
  ['FMRA3M', 'RO', 'INDIRECT CTO STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRA3S', 'RO', 'INDIRECT CTO STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRA4L', 'RO', 'INDIRECT CTO STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT'],
  ['FMRA4M', 'RO', 'INDIRECT CTO STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRA4S', 'RO', 'INDIRECT CTO STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRAEB', 'RO', 'EARLY BIRD OFFER-INDIRECT 2', 'Wholesaler/FIT'],
  ['FMRB1L', 'BB', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT'],
  ['FMRB1M', 'BB', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRB1S', 'BB', 'INDIRECT STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRB3L', 'BB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT'],
  ['FMRB3M', 'BB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRB3S', 'BB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRB4L', 'BB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Wholesaler/FIT'],
  ['FMRB4M', 'BB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRB4S', 'BB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRBEB', 'BB', 'EARLY BIRD OFFER-INDIRECT 2', 'Wholesaler/FIT'],
  ['FMRF3L', 'FB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Wholesaler/FIT'],
  ['FMRF3M', 'FB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRF3S', 'FB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRF4L', 'FB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Wholesaler/FIT'],
  ['FMRF4M', 'FB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRF4S', 'FB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRFEB', 'FB', 'EARLY BIRD OFFER-INDIRECT 2', 'Wholesaler/FIT'],
  ['FMRH3L', 'HB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Wholesaler/FIT'],
  ['FMRH3M', 'HB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRH3S', 'HB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRH4L', 'HB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Wholesaler/FIT'],
  ['FMRH4M', 'HB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRH4S', 'HB', 'INDIRECT CTO STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRHEB', 'HB', 'EARLY BIRD OFFER-INDIRECT 2', 'Wholesaler/FIT'],
  ['FMRI3L', 'AI', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT'],
  ['FMRI3M', 'AI', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRI3S', 'AI', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRI4L', 'AI', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Wholesaler/FIT'],
  ['FMRI4M', 'AI', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Wholesaler/FIT'],
  ['FMRI4S', 'AI', 'INDIRECT CTO ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Wholesaler/FIT'],
  ['FMRIEB', 'AI', 'EARLY BIRD OFFER-INDIRECT 2', 'Wholesaler/FIT'],
  ['FMSEXA', 'RO', 'Super Sales rate Expedia', 'Wholesaler/FIT'],
  ['FMSEXB', 'BB', 'Super Sales rate BB Expedia', 'Wholesaler/FIT'],
  ['GOV', 'RO', 'Government Rate static', 'Company rate'],
  ['HOUSE', 'RO', 'House Use', 'Complimentary'],
  ['HS1', 'RO', 'Employees, Friends and Family - Flexible rate - eligible to ALL points', 'Company rate'],
  ['HS1BRN', 'RO', 'ACCOR OWNER PARTNER RATE 1', 'Accor Loyalty'],
  ['HS3', 'RO', 'Employees, Friends and Family - Saver rate - eligible to ALL points', 'Company rate'],
  ['HS3BRN', 'RO', 'ACCOR OWNER PARTNER RATE 3', 'Accor Loyalty'],
  ['L10RA1', 'RO', 'Lux Member Discount - Classic', 'Discount Card/Membership Program'],
  ['L10RB1', 'BB', 'Lux Member Discount - Classic', 'Discount Card/Membership Program'],
  ['L15RA1', 'RO', 'Lux Member Discount - Silver & Gold', 'Discount Card/Membership Program'],
  ['L15RB1', 'BB', 'Lux Member Discount - Silver & Gold', 'Discount Card/Membership Program'],
  ['L18RA1', 'RO', 'Lux Member Discount - Platinum+', 'Discount Card/Membership Program'],
  ['L18RB1', 'BB', 'Lux Member Discount - Platinum+', 'Discount Card/Membership Program'],
  ['L19', 'RO', 'Leisure Rate/L19', 'Package/Promo'],
  ['LAXXXX', 'RO', 'Static Leisure individual - Room only', 'Wholesaler/FIT'],
  ['LBXXXX', 'BB', 'Static Leisure individual - Bed and Breakfast', 'Wholesaler/FIT'],
  ['LFXXXX', 'FB', 'Static Leisure individual - Full Board', 'Wholesaler/FIT'],
  ['LHXXXX', 'HB', 'Static Leisure individual - Half Board', 'Wholesaler/FIT'],
  ['LIXXXX', 'AI', 'Static Leisure individual - All inclusive', 'Wholesaler/FIT'],
  ['LOCAL', 'RO', 'AAPC Local Staff Rate', 'Accor employee rate'],
  ['LXXX20', 'RO', 'Luxury program Promo 20% MIN5', 'Luxury rates'],
  ['LXXX25', 'RO', 'Luxury program Promo 25% MIN4', 'Luxury rates'],
  ['LXXX30', 'RO', 'Luxury program Promo 30% MIN3', 'Luxury rates'],
  ['LXXXM1', 'RO', 'Luxury program Master offer standard commission (10%)', 'Luxury rates'],
  ['LXXXM2', 'RO', 'Luxury program Master offer 20% commission on Suites', 'Luxury rates'],
  ['LXXXMS', 'RO', 'Luxury program Master offer 15% commission on Suites', 'Luxury rates'],
  ['LXXXP3', 'RO', 'Luxury program Promo Stay 3 Pay 2', 'Luxury rates'],
  ['LXXXP4', 'RO', 'Luxury program Promo Stay 4 Pay 3', 'Luxury rates'],
  ['LXXXP5', 'RO', 'Luxury program Promo Stay 5 Pay 4', 'Luxury rates'],
  ['LXXXPC', 'RO', 'Luxury program Promo Extra Hotel Credit', 'Luxury rates'],
  ['LXXXPX', 'RO', 'Luxury program Promo 10%', 'Luxury rates'],
  ['MCA', 'BB', 'MasterCard Partnership Rate', 'Discount Card/Membership Program'],
  ['ME10EN', 'RO', 'Dis-loyalty Flexible Rate', 'Discount Card/Membership Program'],
  ['ME20EN', 'RO', 'Dis-loyalty Flexible Rate', 'Discount Card/Membership Program'],
  ['ME25EN', 'RO', 'Dis-loyalty Flexible Rate', 'Discount Card/Membership Program'],
  ['ME30EN', 'RO', 'Dis-loyalty Flexible Rate', 'Discount Card/Membership Program'],
  ['ME35EN', 'RO', 'Dis-Loyalty Flexible Rate', 'Discount Card/Membership Program'],
  ['ME50EN', 'RO', 'Dis-loyalty Flexible Rate - opening hotels', 'Discount Card/Membership Program'],
  ['MEOD', 'RO', 'One day meeting', 'Group rate'],
  ['MOBBB', 'BB', 'Mobile Offer BB for Direct', 'Package/Promo'],
  ['MOBC', 'RO', 'ALL - APP OFFER - COMPLIMENTARY BREAKFAST ON WEEKENDS', 'Accor Loyalty'],
  ['MOBRO', 'RO', 'Mobile Offer RO for Direct', 'Package/Promo'],
  ['MODBB', 'BB', 'Modifiable rate BB', 'Rack rate'],
  ['MODIF', 'RO', 'Modification rate', 'Rack rate'],
  ['MRA1', 'RO', 'Member Rate Discount Flexible', 'Accor Loyalty'],
  ['MRB1', 'BB', 'Member Rate Discount Flexible BB', 'Accor Loyalty'],
  ['NPROM1', 'BB', 'GCHUB NONMEM OFFER 1', 'Package/Promo'],
  ['NPROM2', 'BB', 'GCHUB NONMEM OFFER 2', 'Package/Promo'],
  ['NPROM3', 'BB', 'GCHUB NONMEM OFFER 3', 'Package/Promo'],
  ['OFAIEX', 'AI', 'Global Offer - AI EXP', 'Wholesaler/FIT'],
  ['OFBBEX', 'BB', 'Global Offer - BB EXP', 'Wholesaler/FIT'],
  ['OFFAI', 'AI', 'Global Offer - AI', 'Package/Promo'],
  ['OFFBB', 'BB', 'Global Offer - BB', 'Package/Promo'],
  ['OFFBEX', 'FB', 'Global Offer - FB EXP', 'Wholesaler/FIT'],
  ['OFFFB', 'FB', 'Global Offer - FB', 'Package/Promo'],
  ['OFFHB', 'HB', 'Global Offer - HB', 'Package/Promo'],
  ['OFFRO', 'RO', 'Global Offer - RO', 'Package/Promo'],
  ['OFHBEX', 'HB', 'Global Offer - HB EXP', 'Wholesaler/FIT'],
  ['OFROEX', 'RO', 'Global Offer - RO EXP', 'Wholesaler/FIT'],
  ['PAR1', 'RO', 'PARTNERSHIP 1', 'Discount Card/Membership Program'],
  ['PAR2', 'RO', 'PARTNERSHIP 2', 'Discount Card/Membership Program'],
  ['PAR3', 'BB', 'PARTNERSHIP 3', 'Discount Card/Membership Program'],
  ['PAR4', 'BB', 'PARTNERSHIP 4', 'Discount Card/Membership Program'],
  ['PAR5', 'BB', 'PARTNERSHIP 5', 'Discount Card/Membership Program'],
  ['PPARB1', 'BB', 'PARK AND STAY - BREAKFAST INCLUDED', 'Package/Promo'],
  ['PPC', 'RO', 'Exclusive - Partner rate (50% off)', 'Accor Loyalty'],
  ['PPSF15', 'RO', 'PARK, SLEEP AND FLY - 15 DAYS OF PARKING', 'Package/Promo'],
  ['PPSF3', 'RO', 'ACCOR PLUS - PARK, SLEEP AND FLY - 3 DAYS OF PARKING', 'Package/Promo'],
  ['PPSF7', 'RO', 'ACCOR PLUS - PARK, SLEEP AND FLY - 7 DAYS OF PARKING', 'Package/Promo'],
  ['PPSG15', 'RO', 'PARK, SLEEP AND GO - 15 DAYS OF PARKING', 'Package/Promo'],
  ['PPSG3', 'RO', 'PARK, SLEEP AND GO - 3 DAYS OF PARKING', 'Package/Promo'],
  ['PPSG7', 'RO', 'PARK, SLEEP AND GO - 7 DAYS OF PARKING', 'Package/Promo'],
  ['PRB1C', 'BB', 'ACCOR PLUS - ROMANTIC ESCAPES - BREAKFAST INCLUDED  - CHAMPAGNE AND LATE CHECK OUT', 'Package/Promo'],
  ['PRB1W', 'BB', 'ACCOR PLUS - ROMANTIC ESCAPES - BREAKFAST INCLUDED  - WINE AND LATE CHECK OUT', 'Package/Promo'],
  ['PROM1', 'BB', 'Local Offer – Dual Membership (can be customized by hotel)', 'Package/Promo'],
  ['PROM2', 'BB', 'Local Offer – Dual Membership (can be customized by hotel)', 'Package/Promo'],
  ['PROM3', 'BB', 'Local Offer – Dual Membership (can be customized by hotel)', 'Package/Promo'],
  ['PSB3M', 'BB', 'WELLNESS AND SPA STAY', 'Package/Promo'],
  ['PSB3S', 'BB', 'WELLNESS AND SPA DISCOVERY STAY', 'Package/Promo'],
  ['PSH3M', 'HB', 'GOURMET AND SPA STAY', 'Package/Promo'],
  ['PSH3S', 'HB', 'GOURMET AND SPA DISCOVERY STAY', 'Package/Promo'],
  ['R1D10', 'RO', 'Dynamic Flexible Rate -10%', 'Company rate'],
  ['R1D11', 'RO', 'Dynamic Flexible Rate -11%', 'Company rate'],
  ['R1D12', 'RO', 'Dynamic Flexible Rate -12%', 'Company rate'],
  ['R1D13', 'RO', 'Dynamic Flexible Rate -13%', 'Company rate'],
  ['R1D14', 'RO', 'Dynamic Flexible Rate -14%', 'Company rate'],
  ['R1D15', 'RO', 'Dynamic Flexible Rate -15%', 'Company rate'],
  ['R1D16', 'RO', 'Dynamic Flexible Rate -16%', 'Company rate'],
  ['R1D17', 'RO', 'Dynamic Flexible Rate -17%', 'Company rate'],
  ['R1D18', 'RO', 'Dynamic Flexible Rate -18%', 'Company rate'],
  ['R1D19', 'RO', 'Dynamic Flexible Rate -19%', 'Company rate'],
  ['R1D5', 'RO', 'Dynamic Rate -5%', 'Company rate'],
  ['R1D9', 'RO', 'Dynamic Flexible Rate -9%', 'Company rate'],
  ['R3D5', 'RO', 'Dynamic Rates -5%', 'Company rate'],
  ['R4D5', 'RO', 'Dynamic Rates -5%', 'Company rate'],
  ['RA1', 'RO', 'FLEXIBLE RATE', 'Rack rate'],
  ['RA1L', 'RO', 'STAY LONGER AND SAVE - FLEXIBLE RATE - LONG STAY', 'Rack rate'],
  ['RA1M', 'RO', 'STAY LONGER AND SAVE - FLEXIBLE RATE - MEDIUM STAY', 'Rack rate'],
  ['RA1S', 'RO', 'STAY LONGER AND SAVE - FLEXIBLE RATE - SHORT STAY', 'Rack rate'],
  ['RA3', 'RO', 'SAVER RATE', 'Rack rate'],
  ['RA3L', 'RO', 'STAY LONGER AND SAVE RATE - LONG STAY', 'Rack rate'],
  ['RA3M', 'RO', 'STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Rack rate'],
  ['RA3S', 'RO', 'STAY LONGER AND SAVE RATE - SHORT STAY', 'Rack rate'],
  ['RA4', 'RO', 'ADVANCE SAVER RATE', 'Rack rate'],
  ['RA4L', 'RO', 'STAY LONGER AND SAVE RATE - LONG STAY', 'Rack rate'],
  ['RA4M', 'RO', 'STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Rack rate'],
  ['RA4S', 'RO', 'STAY LONGER AND SAVE RATE - SHORT STAY', 'Rack rate'],
  ['RAC', 'RO', 'Rack Rate/RAC', 'Rack rate'],
  ['RACINR', 'RO', 'Rack Rate India (for taxes only)', 'Rack rate'],
  ['RAEB', 'RO', 'EARLY BIRD OFFER', 'Package/Promo'],
  ['RAF', 'RO', 'EVENT PREPAID RATE', 'Rack rate'],
  ['RAF2', 'RO', 'SEMI-FLEXIBLE RATE', 'Rack rate'],
  ['RB1', 'BB', 'FLEXIBLE RATE - BREAKFAST INCLUDED', 'Rack rate'],
  ['RB1D10', 'BB', 'Dynamic Rate BB -10%', 'Company rate'],
  ['RB1D11', 'BB', 'Dynamic Rate BB -11%', 'Company rate'],
  ['RB1D12', 'BB', 'Dynamic Rate BB -12%', 'Company rate'],
  ['RB1D13', 'BB', 'Dynamic Rate BB -13%', 'Company rate'],
  ['RB1D14', 'BB', 'Dynamic Rate BB -14%', 'Company rate'],
  ['RB1D15', 'BB', 'Dynamic Rate BB -15%', 'Company rate'],
  ['RB1D16', 'BB', 'Dynamic Rate BB -16%', 'Company rate'],
  ['RB1D17', 'BB', 'Dynamic Rate BB -17%', 'Company rate'],
  ['RB1D18', 'BB', 'Dynamic Rate BB -18%', 'Company rate'],
  ['RB1D5', 'BB', 'Dynamic Rate BB -5%', 'Company rate'],
  ['RB1D9', 'BB', 'Dynamic Rate BB -9%', 'Company rate'],
  ['RB1FCM', 'BB', 'RB1 FCM Breakfast Plus', 'Travel agency rates'],
  ['RB1L', 'BB', 'STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - LONG STAY', 'Rack rate'],
  ['RB1M', 'BB', 'STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Rack rate'],
  ['RB1S', 'BB', 'STAY LONGER AND SAVE - FLEXIBLE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Rack rate'],
  ['RB3', 'BB', 'SAVER RATE- BREAKFAST INCLUDED', 'Rack rate'],
  ['RB3D5', 'BB', 'Dynamic Rates RB3 -5%', 'Company rate'],
  ['RB3L', 'BB', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Rack rate'],
  ['RB3M', 'BB', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Rack rate'],
  ['RB3S', 'BB', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Rack rate'],
  ['RB4', 'BB', 'ADVANCE SAVER RATE - BREAKFAST INCLUDED', 'Rack rate'],
  ['RB4D5', 'BB', 'Dynamic Rates RB4 -5%', 'Company rate'],
  ['RB4L', 'BB', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - LONG STAY', 'Rack rate'],
  ['RB4M', 'BB', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - MEDIUM STAY', 'Rack rate'],
  ['RB4S', 'BB', 'STAY LONGER AND SAVE RATE - BREAKFAST INCLUDED - SHORT STAY', 'Rack rate'],
  ['RBEB', 'BB', 'EARLY BIRD OFFER', 'Package/Promo'],
  ['RBF', 'BB', 'EVENT PREPAID RATE - BREAKFAST INCLUDED', 'Package/Promo'],
  ['RBF2', 'BB', 'EVENT SEMI-FLEXIBLE RATE - BREAKFAST INCLUDED', 'Rack rate'],
  ['RC1', 'ASPAC', 'ALL - FLEXIBLE RATE - COMPLIMENTARY BREAKFAST', 'Accor Loyalty'],
  ['RC3', 'ASPAC', 'ALL - SAVER RATE - COMPLIMENTARY BREAKFAST', 'Accor Loyalty'],
  ['RC3L', 'ASPAC', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - LONG STAY', 'Accor Loyalty'],
  ['RC3M', 'ASPAC', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - MEDIUM STAY', 'Accor Loyalty'],
  ['RC3S', 'ASPAC', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - SHORT STAY', 'Accor Loyalty'],
  ['RC4', 'ASPAC', 'ALL - ADVANCE SAVER RATE - COMPLIMENTARY BREAKFAST', 'Accor Loyalty'],
  ['RC4L', 'ASPAC', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - LONG STAY', 'Accor Loyalty'],
  ['RC4M', 'ASPAC', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - MEDIUM STAY', 'Accor Loyalty'],
  ['RC4S', 'ASPAC', 'ALL - STAY LONGER AND SAVE RATE - COMPLIMENTARY BREAKFAST - SHORT STAY', 'Accor Loyalty'],
  ['RCF', 'RO', 'SPECIAL EVENT RATE - COMPLIMENTARY BREAKFAST', 'Accor Loyalty'],
  ['RCF2', 'RO', 'SPECIAL EVENT RATE - COMPLIMENTARY BREAKFAST', 'Accor Loyalty'],
  ['RDMDA', 'RO', 'ACCOR PLUS MOBILE ONLY OFFER - &0% OFF', 'Package/Promo'],
  ['RECC', 'RO', 'LUXURY RESIDENCE OWNER RECIPROCAL USE PROGRAM RATE', 'Accor employee rate'],
  ['REMCL1', 'RO', 'FLEXIBLE RATE : GET A 20 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo'],
  ['REMGD1', 'RO', 'FLEXIBLE RATE : GET A 50 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo'],
  ['REMPL1', 'RO', 'FLEXIBLE RATE : GET A 60 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo'],
  ['REMSI1', 'RO', 'FLEXIBLE RATE : GET A 35 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo'],
  ['RESCL1', 'RO', 'FLEXIBLE RATE : GET A 50 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo'],
  ['RESGD1', 'RO', 'FLEXIBLE RATE : GET A 100 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo'],
  ['RESON1', 'RO', 'AccorHotels Residential Owner Platinum', 'Accor Loyalty'],
  ['RESPL1', 'RO', 'FLEXIBLE RATE : GET A 120 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo'],
  ['RESSI1', 'RO', 'FLEXIBLE RATE : GET A 70 USD CREDIT FOR YOUR RESORT STAY', 'Package/Promo'],
  ['RF1', 'FB', 'FLEXIBLE RATE - FULL BOARD', 'Rack rate'],
  ['RF3', 'FB', 'SAVER RATE - FULL BOARD', 'Rack rate'],
  ['RF3L', 'FB', 'STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Rack rate'],
  ['RF3M', 'FB', 'STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Rack rate'],
  ['RF3S', 'FB', 'STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Rack rate'],
  ['RF4', 'FB', 'ADVANCE SAVER RATE - FULL BOARD', 'Rack rate'],
  ['RF4L', 'FB', 'STAY LONGER AND SAVE RATE - FULL BOARD - LONG STAY', 'Rack rate'],
  ['RF4M', 'FB', 'STAY LONGER AND SAVE RATE - FULL BOARD - MEDIUM STAY', 'Rack rate'],
  ['RF4S', 'FB', 'STAY LONGER AND SAVE RATE - FULL BOARD - SHORT STAY', 'Rack rate'],
  ['RFEB', 'FB', 'EARLY BIRD OFFER', 'Package/Promo'],
  ['RH1', 'HB', 'FLEXIBLE RATE - HALF BOARD', 'Rack rate'],
  ['RH3', 'HB', 'SAVER RATE - HALF BOARD', 'Rack rate'],
  ['RH3L', 'HB', 'STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Rack rate'],
  ['RH3M', 'HB', 'STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Rack rate'],
  ['RH3S', 'HB', 'STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Rack rate'],
  ['RH4', 'HB', 'ADVANCE SAVER RATE - HALF BOARD', 'Rack rate'],
  ['RH4L', 'HB', 'STAY LONGER AND SAVE RATE - HALF BOARD - LONG STAY', 'Rack rate'],
  ['RH4M', 'HB', 'STAY LONGER AND SAVE RATE - HALF BOARD - MEDIUM STAY', 'Rack rate'],
  ['RH4S', 'HB', 'STAY LONGER AND SAVE RATE - HALF BOARD - SHORT STAY', 'Rack rate'],
  ['RHEB', 'HB', 'EARLY BIRD OFFER', 'Package/Promo'],
  ['RI1', 'AI', 'ALL INCLUSIVE - FLEXIBLE RATE', 'Rack rate'],
  ['RI3', 'AI', 'ALL INCLUSIVE - SAVER RATE', 'Rack rate'],
  ['RI3L', 'AI', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Rack rate'],
  ['RI3M', 'AI', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Rack rate'],
  ['RI3S', 'AI', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Rack rate'],
  ['RI4', 'AI', 'ALL INCLUSIVE - ADVANCE SAVER RATE', 'Rack rate'],
  ['RI4L', 'AI', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - LONG STAY', 'Rack rate'],
  ['RI4M', 'AI', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - MEDIUM STAY', 'Rack rate'],
  ['RI4S', 'AI', 'ALL INCLUSIVE - STAY LONGER AND SAVE RATE - SHORT STAY', 'Rack rate'],
  ['RIEB', 'AI', 'EARLY BIRD OFFER', 'Package/Promo'],
  ['SEN', 'RO', 'Senior Citizen Rate', 'Travel agency rates'],
  ['STARP', 'RO', 'STAR PLUS', 'Travel agency rates'],
  ['SUPBB', 'BB', 'Super Sale BB Rate', 'Package/Promo'],
  ['SUPERS', 'RO', 'Super Sales rate', 'Package/Promo'],
  ['SUPHB', 'HB', 'Super Sale HB Rate', 'Package/Promo'],
  ['TGLL', 'BB', 'Leisure Groups', 'Group rate'],
  ['TGLLHB', 'HB', 'Leisure Groups HB', 'Group rate'],
  ['TRB1PX', 'BB', 'Accor SME programme with TMCs', 'Company rate'],
  ['VCHIC', 'RO', 'VERYCHIC ROOM ONLY', 'Package/Promo'],
  ['VCHICB', 'BB', 'VERYCHIC BB', 'Package/Promo'],
  ['VCHICH', 'HB', 'VERYCHIC HALF BOARD', 'Package/Promo'],
  ['VCT', 'RO', 'VERY CHIC TONIGHT RO', 'Package/Promo'],
  ['VCTBB', 'BB', 'VERY CHIC TONIGHT BB', 'Package/Promo'],
  ['VITA', 'RO', 'IBIS SPORT', 'Group rate'],
  ['VOUC10', 'RO', 'Universal Voucher 10', 'Package/Promo'],
  ['VOUC11', 'RO', 'Universal Voucher 11', 'Package/Promo'],
  ['VOUC12', 'RO', 'Universal Voucher 12', 'Package/Promo'],
  ['VOUC14', 'RO', 'Universal Voucher 14', 'Package/Promo'],
  ['VOUC15', 'RO', 'Universal Voucher 15', 'Package/Promo'],
  ['VOUCH1', 'RO', 'Universal Voucher 1', 'Package/Promo'],
  ['VOUCH2', 'RO', 'Universal Voucher 2', 'Package/Promo'],
  ['VOUCH3', 'RO', 'Universal Voucher 3', 'Package/Promo'],
  ['VOUCH4', 'RO', 'Universal Voucher 4', 'Package/Promo'],
  ['VOUCH5', 'RO', 'Universal Voucher 5', 'Package/Promo'],
  ['VOUCH6', 'RO', 'Universal Voucher 6', 'Package/Promo'],
  ['VOUCH7', 'RO', 'Universal Voucher 7', 'Package/Promo'],
  ['VOUCH8', 'RO', 'Universal Voucher 8', 'Package/Promo'],
  ['VOUCH9', 'RO', 'Universal Voucher 9', 'Package/Promo'],
  ['WORKIT', 'RO', 'Ennismore Business Travel', 'Accor employee rate'],];

export interface RateInfo {
  /** The rate code, upper-cased. */
  code: string;
  /**
   * 'RO' | 'BB' | 'HB' | 'FB' | 'AI' for a simple meal plan, or one of the three
   * cannot-answer cases: 'ASPAC' | 'CONTRACT' | 'PACKAGE'. See the header.
   */
  plan: string;
  /** The rate's name in the referential, e.g. 'FLEXIBLE RATE - BREAKFAST INCLUDED'. */
  name: string;
  /** The rate family, e.g. 'Group rate', 'Rack rate', 'Wholesaler/FIT'. */
  family: string;
}

const BY_CODE: Record<string, RateInfo> = {};
for (const [code, plan, name, family] of RAW) {
  BY_CODE[code] = { code, plan, name, family };
}

/** Every code in the referential. Exposed for tests and for the unknown-code report. */
export const RATE_CODE_COUNT = RAW.length;

/**
 * Exact-match lookup. Returns null for a code the global referential does not list - which is
 * normal: property-local codes such as C01MRO, LDR, C20, TRIPRO and CREWESR are configured in
 * the property's own Opera and never appear here.
 */
export function lookupRate(rateCode: string | undefined | null): RateInfo | null {
  if (!rateCode) return null;
  return BY_CODE[String(rateCode).trim().toUpperCase()] ?? null;
}

/**
 * Does this rate include breakfast?
 *
 *   true   the rate includes it (BB / HB / FB / AI, or ASPAC where we are)
 *   false  the rate is Room Only
 *   null   THE RATE CANNOT ANSWER. Either the code is not in the referential, or it is
 *          contract- or package-dependent. Callers must not collapse null to false: that is
 *          exactly the mistake that refused breakfast to guests who were owed it.
 */
export function breakfastFromRate(rateCode: string | undefined | null): boolean | null {
  const info = lookupRate(rateCode);
  if (!info) return null;
  switch (info.plan) {
    case 'BB':
    case 'HB':
    case 'FB':
    case 'AI':
      return true;
    // Chiang Mai is ASPAC, where the override makes these Bed & Breakfast every day.
    case 'ASPAC':
      return true;
    case 'RO':
      return false;
    // 'CONTRACT' and 'PACKAGE' are unanswerable from the rate alone.
    default:
      return null;
  }
}

/** True when the rate's inclusion is set by a group block contract rather than the rate. */
export function isContractDependent(rateCode: string | undefined | null): boolean {
  return lookupRate(rateCode)?.plan === 'CONTRACT';
}

/** True when the code reads as Room Only but the ASPAC override makes it Bed & Breakfast. */
export function isAspacOverride(rateCode: string | undefined | null): boolean {
  return lookupRate(rateCode)?.plan === 'ASPAC';
}
